### ISSUE TITLE
Possibility to integrate with other tools

### ISSUE THREAD

**Issue by heniotierra** [KlausSchaefers/quant-ux#1]
Hi,

Quant-UX is an awesome tool! I was wondering whether it's possible to integrate it with external tools/websites or if that's a planned feature, since I am planning on building a larger scope application, which involves prototyping apps as a feature, and it would be great to be able to integrate Quant-UX in this project, since it's so rich and powerful!

 Congrats for building it, and many thanks for making it open source! :heart:

**Comment by KlausSchaefers** [comment]
Hi,

Quant-UX is build in Vue.js, so everything is a component. If you build in Vue.js the integration should be super easy. If you use React or Angular it should be also doable, but it might require a more complex setup. If needed, I could publish the entire tool as an NPM and you could include it easily. Also, I could add some extension points, just let me know what you need!

Klaus

**Comment by KlausSchaefers** [comment]
Working on it
