### ISSUE TITLE
Feature: can there be recursive inheritance for master screens ?!

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#100]
Master screens are really great, but at least on my first experience, it would be great it you could create a base master-screen, then have a second level of different layouts, using that master screen, and being themselves master screens. And I don't know, these two levels, maximum another one would be sufficient, at least for me. Infinite recursion master-screens could be a good thing also, don't know...
Can this be implemented natively, rather easily or is it a hard thing to consider ?!
I guess, you can resort to components, for the second level of master screens (or to duplicating the first level of master-screens), but this somehow kills the elegancy you provided with this wonderful concept.
Thanks !

**Comment by Equilibrier** [comment]
Ok, I didn't saw the possibility to add multiple master-screens, this is somehow a compensation for the no inheritance possibility, but if I personally would have to choose between multiple inheritance of one-level-master-screens (like now) and one-single-inherit of multiple-level-master-screens (what am I proposing) I would choose the second as more intuitive with only one explicit template for any screen, but that template being constructed of multiple layers of other templates.
I'm not a designer, I just started, with Figma, two months ago, and now with QuantUX (and btw, I think I will never go back to Figma again), so don't take my ideas into granted as from an experienced designer, just from a developer's point of view, and you know we developers have a logical thinking, which not always matches the on terrain needs.

**Comment by KlausSchaefers** [comment]
You can inherited multiple screens. Would this work?

**Comment by KlausSchaefers** [comment]
Ok, good to know

**Comment by KlausSchaefers** [comment]
I decided to not fit this one.. Multiple inheritance will create a mess to most users.
