### ISSUE TITLE
Feature: common JS script for sharing common functions

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#107]
If you, as a designer&developer, want to take this more seriously and build a statefull like app prototype, you will need some business-logic code, so a simple mechanism like global functions should be a demand.
You could just add a <> widget, which is flagged as global (no need for being a click-trigger, value-trigger, just a loaded-trigger) which means all functions defined in there are visible in any later script.

**Comment by KlausSchaefers** [comment]
For complex prototypes with a lot of code, we developed the Luisa framework.

https://luisa.cloud/help/luisa_framework.html

**Comment by Equilibrier** [comment]
I really think you were too hurried in closing this ticket...

**It is not a bug to be fixed, it is a feature, and no, I cannot use the Luisa framework simply because I want to code the final app in something else then Vue, but I want the prototype to be as similar and it can be to the real final app.** And this is where your <> widgets come very nice into place. I'm willing to code the dynamics of the prototype myself, as complex as it might be, using the data bindings as (prototype)app-state and I'm sure others would things as me.
The only thing I requested was a very simple thing: there should be <> widgets that they provide JS code for global usage, rather than by making a new widget or a simple combobox on these already implemented, with something like "global" vs "simple" (script).

Otherwise, I would have to bring in the whole abstract logic of my prototype-app in every <script> I insert in the canvas.
How would it be to insert 10x times more code than bellow, in more than 10-15 scripts, and then try to modify something in a certain function?:

```
function prevPageExists(rootRefs=["prod_categories"]) {
	let root = data.pages;
	for (k of rootRefs) root = root[k];
    return root.pages[root.cpage - 1] != undefined;
}
function nextPageExists(rootRefs=["prod_categories"]) {
	let root = data.pages;
	for (k of rootRefs) root = root[k];
    return root.pages[root.cpage + 1] != undefined;
}

function refreshPage(rootRefs=["prod_categories"], container=data.categories) {
	let root = data.pages;
	for (k of rootRefs) root = root[k];
	let rootI = data.instant;
	for (k of rootRefs) rootI = rootI[k];
	
    let ids = root.pages[root.cpage];
    ids = ids === undefined ? [] : ids;
    rootI.page = [];
    for (let iid of ids) {
        const id = iid.id;
        rootI.page.push({
            img: container[id].img,
            label: container[id].label
        });
    }
    return rootI.page.length > 0;
}

function resetCategoriesPage(cpage) {
	let rrefs = ["prod_categories"]
    data.pages.prod_categories.cpage = cpage;
    refreshPage(rootRefs=rrefs, container=data.categories);
    
    let screen = qux.getScreen('CHP_page1')
    let pw = screen.getGroup('butt-prev');
    let nw = screen.getGroup('butt-next');
    if (!prevPageExists(rrefs)) {
        pw.hide();
    }
    else {
        pw.show();
    }
    if (!nextPageExists(rrefs)) {
        nw.hide();
    }
    else {
        nw.show();
    }
    
    screen.getGroup('pc0').hide();
    screen.getGroup('pc1').hide();
    screen.getGroup('pc2').hide();
    screen.getGroup('pc3').hide();
    screen.getGroup('pc4').hide();
    screen.getGroup('pc5').hide();
    
    if (data.instant.prod_categories.length > 0) {
        screen.getGroup('pc0').show();
    }
    if (data.instant.prod_categories.length > 1) {
        screen.getGroup('pc1').show();
    }
    if (data.instant.prod_categories.length > 2) {
        screen.getGroup('pc2').show();
    }
    if (data.instant.prod_categories.length > 3) {
        screen.getGroup('pc3').show();
    }
    if (data.instant.prod_categories.length > 4) {
        screen.getGroup('pc4').show();
    }
    if (data.instant.prod_categories.length > 5) {
        screen.getGroup('pc5').show();
    }
}
```
