### ISSUE TITLE
Feature: global <> scripts for global JS code

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#110]
@KlausSchaefers 
I really think you were too hurried in closing the last ticket over this issue, and without giving me the possibility to explain more of this need/request...

Shortly: **It is not a bug to be fixed, it is a feature, and no, I cannot use the Luisa framework simply because I want to code the final app in something else than Vue, but I want the prototype to be as similar and it can be to the real final app.** And this is where your <> widgets come very nice into place. I'm willing to code the dynamics of the prototype myself, as complex as it might be, using the data bindings as (prototype)app-state and I'm sure others would think as me.

And I surely was not requesting something too difficult, I might estimate it myself as being 20% the difficulty of what it was already implemented for the <> widgets.

The only thing I asked was a very simple thing: there should be <> widgets that *provide JS code for global usage*; 
maybe by making a new widget or a simple combobox with something like "global" vs "simple" (script) on those already implemented.

**Otherwise, I would have to bring in the ^entire^ abstract logic of my prototype-app in every <script> I insert in the canvas.
How would it be to insert 10x times more code than bellow, in more than 10-15 scripts, and then try to modify something in a certain function?:**

```
function prevPageExists(rootRefs=["prod_categories"]) {
	let root = data.pages;
	for (k of rootRefs) root = root[k];
    return root.pages[root.cpage - 1] != undefined;
}
function nextPageExists(rootRefs=["prod_categories"]) {
	let root = data.pages;
	for (k of rootRefs) root = root[k];
    return root.pages[root.cpage + 1] != undefined;
}

function refreshPage(rootRefs=["prod_categories"], container=data.categories) {
	let root = data.pages;
	for (k of rootRefs) root = root[k];
	let rootI = data.instant;
	for (k of rootRefs) rootI = rootI[k];
	
    let ids = root.pages[root.cpage];
    ids = ids === undefined ? [] : ids;
    rootI.page = [];
    for (let iid of ids) {
        const id = iid.id;
        rootI.page.push({
            img: container[id].img,
            label: container[id].label
        });
    }
    return rootI.page.length > 0;
}

function resetCategoriesPage(cpage) {
	let rrefs = ["prod_categories"]
    data.pages.prod_categories.cpage = cpage;
    refreshPage(rrefs, data.categories);
    
    let screen = qux.getScreen('CHP_page1')
    let pw = screen.getGroup('butt-prev');
    let nw = screen.getGroup('butt-next');
    if (!prevPageExists(rrefs)) {
        pw.hide();
    }
    else {
        pw.show();
    }
    if (!nextPageExists(rrefs)) {
        nw.hide();
    }
    else {
        nw.show();
    }
    
    screen.getGroup('pc0').hide();
    screen.getGroup('pc1').hide();
    screen.getGroup('pc2').hide();
    screen.getGroup('pc3').hide();
    screen.getGroup('pc4').hide();
    screen.getGroup('pc5').hide();
    
    if (data.instant.prod_categories.length > 0) {
        screen.getGroup('pc0').show();
    }
    if (data.instant.prod_categories.length > 1) {
        screen.getGroup('pc1').show();
    }
    if (data.instant.prod_categories.length > 2) {
        screen.getGroup('pc2').show();
    }
    if (data.instant.prod_categories.length > 3) {
        screen.getGroup('pc3').show();
    }
    if (data.instant.prod_categories.length > 4) {
        screen.getGroup('pc4').show();
    }
    if (data.instant.prod_categories.length > 5) {
        screen.getGroup('pc5').show();
    }
}
```

**PS: Heck, you could do the bellow referenced INSERTION phase in the QUX code, rather than by requesting me, the user, to do it. :)**

**Comment by Equilibrier** [comment]
If you want, other ideas for easy integration on some kind of similar functionality, would be to provide the <> script the possibility to use the require-from-url (are you using nodejs on the server side for these scripts ?!) or import <url>, somehow.
For now, neither works, 'require' is not a known instruction, require-from-url neither, and the 'import' instruction generates a "Cannot use import statement outside a module". If import would have worked, the user (me) could host it's global js files/file remote and just reference it in the <> widgets, manually.
Is this a simple thing to do ?!
If you do not have the time, can you provide me the info in the src-code, where I can do this, please ?
For this functionality to happen for me, can I somehow fork the source-code but continue using the cloud version of QUX, or do I need to install it on a dedicated server ?

**Comment by KlausSchaefers** [comment]
Hi,

I was long thinking about code sharing. In the end I didn't do it because I belief in QUX scripts should be simple. The Code editor is pretty basic (ACE), so the development experience will always be bad when compared to something like VS Code. For such use cases I developed Luisa. One can still code (pretty much in Vanilla JS) in a proper IDE, while designing an in proper tool. 

I could think about making a kind of global script which content is always pasted before the actually script. So the code will be

```JS
eval(globalScript + currentScript)
```

But I still need a little time to think this through. The development experience would be still bad. One will need to jump between different script elements all the time.  So I am not 100% convinced. Any Idea how to make this better?

**Comment by KlausSchaefers** [comment]
I use web workers. They support a importScripts:

https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts

So if you place the script somewhere, it should be able to download from your server.

**Comment by Equilibrier** [comment]
Thanks for responding !

> But I still need a little time to think this through. The development experience would be still bad. One will need to jump between different script elements all the time. So I am not 100% convinced. Any Idea how to make this better?

That's why I "invented" the global-scripts. You would code your own prototype-business-logic API in there and in individual scripts (the ones implemented right now) you would just use functions, and the code might even get simpler than before (now, you have to code the things from scratch in every node, as look, the code snippet I added was only for adding pagination to a custom-grid like panel).
So if you ask me, it surely is a motivation for this global scripts, even in your own thinking when you said "I belief in QUX scripts should be simple". Those global scripts would give you the possibility to simplify the triggered/loaded scripts very very much.
I personally don't need VSCode like experience in this, only because this is a prototype and not the final app, so I would just write code that makes the prototype behave like the final app, so no fuss, and no pretences on this.

**Comment by Equilibrier** [comment]
> So if you place the script somewhere, it should be able to download from your server. Take a look here:

https://github.com/KlausSchaefers/quant-ux/blob/master/src/core/engines/ScriptWorker.js

Today I downloaded the code, deployed quantUX as on a local raspberry pi 4 server, it ran ok, it loaded my previous app from the cloud (the mongodb server is not well configured yet), so I was looking through on a first glance, and I found the ScriptWorker.js, which you confirm is the startpoint for this. Also looked into ScriptEditor.vue, ScriptEngine.js and so on.
The fact is since I didn't developed with Vue before, and since I'm no advanced tech JS developer, it still was difficult for me to see exactly where is the actual line that runs the script, and where is the script contained.
Maybe you can help me with that, a simple pseudo-code in the ScriptWorker.js how you should do the "globalScript + currentScript" part, as it's evident you don't use eval() for executing the code.
I didn't worked with workers before, I can learn, np, but I'm still in doubt on where do you actually run the code, and btw I don't see any "importScripts" in any of your source-code.

A more simpler idea if you do not like the global-scripts concept, is making a settings panel where you can specify one or more rest urls from where global js-code can be provided, and upon executing, download all of these JS files, concatenate them and then append every <> script with that. Seems like more work to do on this approach but at least it's not breaking your thinking paradigm and quantUX features board.
Can you provide me with help about writing this code ? I can write it on my own server know, but please do give me some hints, especially on the running JS in ScriptWorker.js part...
Thanks!

**Comment by KlausSchaefers** [comment]
HI,

you should be able to load an external script from the script widget, by using 

```
importScripts('server.com/script.js')

functionDefinedInScript()

```

**Comment by Equilibrier** [comment]
It worked, thanks, BUT :), only on the first time. If I run the simulator the second time, I will get a "A network error occurred." or a "Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://equilibrium.go.ro/quantux-apis/smartbasket/js' failed to load."; and when I clean the cookies or restart the browser, it works (the first time) once again, and from the second time it will throw the above errors. Interesting to know that Firefox always throws the first error, while Chrome, Chromium/Edge throws the second.

Can you help me debug this, please ?

**Comment by KlausSchaefers** [comment]
Hm, I have no experience with this. It will take me a while...

Equilibrier ***@***.***> schrieb am So., 3. Juli 2022, 01:54:

**Comment by KlausSchaefers** [comment]
In Canvas.vue there is a setSettings() and so on. Take a look there.

**Comment by KlausSchaefers** [comment]
Hi,

I just tried import script. This works for me every time, also on Android and iOS. 

The shared code is the following:

```js
function sharedMethod (data) {
    console.debug('sharedMethod() > enter', data)
    data.shared = 'Shared...'
}
```

The snipped this:

![image](https://user-images.githubusercontent.com/7108416/177195022-1b166bc0-6dbe-453b-9276-0873b9de47ff.png)

I believe this might be related to your PC. You have any ad-blockers installed or so? Can you try a different machine?

**Comment by Equilibrier** [comment]
Yes, I didn't said importScripts doesn't work ;).
You are giving it a local file, I assume it works fine.

On my scenario I gave it a remote file. This is where things were not ok.
I'm assuming it has to do with some security options on the browser, because on different browsers I have different errors popping out. But nevertheless, even if I would discover those settings, I cannot deploy a complete browser to a client, so that he sees the demo... 

So I will stick with the "pre-appending" implementation. This really worked.

**Comment by Equilibrier** [comment]
I saw it:

`setSettings (s){
			this.mergeSettings(s)
			this._setStatus("matcSettings",this.settings);
			this.applySettings(this.settings);
			this.rerender();
		}`


But it doesn't seem to do persistency, any of the sub-functions.
I looked carefully on each of them.
And although I added my field in this "class" I didn't do any persistency.

Look, you also have this:
`initSettings (){
			this.logger.log(0, "initSettings", "enter > " );
			/**
			 * default settings.
			 * Since 3.0.43 we snapp by default to top left corner
			 */
			this.settings = {
				canvasTheme : "MatcLight",
				lineColor : "#3787f2",
				lineWidth : 1,
				storePropView : true,
				moveMode : "ps",
				startToolsOnKeyDown : true,
				mouseWheelMode : "scroll",
				renderLines : false,
				snapGridOnlyToTopLeft: true,
				keepColorWidgetOpen: true,
				layerListVisible: false,
				showRuler: true,
				fastRender: false,
				hasProtoMoto: false,
				zoomSnapp: true,
				selectMove: true,
				hasDesignToken: true,
				globalScriptUrlsEnabled: {}
			};

			var s = this._getStatus("matcSettings");
			if (s){
				this.mergeSettings(s)
			} else {
				this.logger.log(2,"initSettings", "exit>  no saved settings" );
			}
			this.applySettings(this.settings);

		},`

it just plainly sets some defaults, it doesn't read the json file anywhere; I would expect a read from a remove/local file in here.

So I'm confused, but I'll dig some more...

**Comment by Equilibrier** [comment]
I have another question now: how do I obtain the canvas.getSettings() from anywhere ? You seem to have this "canvas" attribute on some "classes" but not on all of them, and I'm a bit confussed, as even on those places where this.canvas works, I don't see the attribute setting on anywhere, and I looked in the code and it doesn't seem you are using a global mixin also...

**Comment by Equilibrier** [comment]
Ok, I'm progressing but slow. I see you don't have a DIP provider or something like that, you instead have multiple repeated setters, like setModel(m), setCanvas(c), so it's very messy because it doesn't seem you have a central starting point where you provide these references but I'll try to follow up the red line, to see at least where the canvas it set (for now I see it has something to do with the Controller...).

**Comment by Equilibrier** [comment]
This is what I have until now:

![image](https://user-images.githubusercontent.com/106168205/177215362-b4fa1f73-c92e-47a1-826c-49eceea07d72.png)

**Comment by KlausSchaefers** [comment]
Hi,

The settings are saved in the browser as local storage. So your script will
not be able to run in any client or other browser in the same Maschine.

Can you put the script in the public/test folder and load it via
importScript? This is what I have done.



Equilibrier ***@***.***> schrieb am Mo., 4. Juli 2022, 21:52:

**Comment by KlausSchaefers** [comment]
Are you serving the script over Https?


Klaus Schaefers ***@***.***> schrieb am Di., 5. Juli 2022,
00:02:

**Comment by Equilibrier** [comment]
**Finally I did it. It works now.**
Men, it was something. I had some naive mistakes on my own, so that's why I thought Canvas is not persisting the settings, but it does and now I know, it's in local-storage...
_Please don't get mad on me for saying this, and you might know that on your own, but the code should really be refactored, as it took me almost two days on something that I would implement in 3, max 5 hours on a not-known platform and not-known code. Maybe I can help you do that in the future if you want, but certainly I would need to understand all of your code, and draw lots, lots of diagrams, like the previous one, because it is spaghetti and if you touch something in one place you won't know if any side effects would appear..._

Anyways..

> The settings are saved in the browser as local storage. 

It's good to know, so I might think abandoning the enabled/disabled checkboxes mechanism in the settings, because the client would not have those settings and it might bring to broken-prototypes. So the checkboxes would be good just for debugging-purposes, and I might write that on a help file (next thing to do). I think I will let them be, and overwrite them with true0by-default on the client (where the local-storage would not contain these booleans).

> Can you put the script in the public/test folder and load it via
importScript? This is what I have done.

I ended up using fetch API anytime a run is made and preprending the code manually, before giving it to the ScriptWorker (so I'm doing this in ScripEditor.vue, which is natural), because it was the most simpler, it is not consuming any bandwidth (how much JS code could you import...?!) and it has the advantage of transparency (since the code is remote,  you will edit it remote, but you won't have to refresh the window to be sure it is in /public/test folder next time you want to run the script...).

I would leave it like so, but I will try to write a help page for this.
And then, I'm happy, I would have liked to not using remote urls but plain code, but unfortunately, my comments-as-storage-base for this would not work, because the textarea on the comments is really small. But I'm still happy, I can work with that and continuing my prototype, since I'm late with it...

_PS: I can maintain my changes on my fork, so I can only use it, but if you think you are interested in how the things went, you can pin your interest in here, and I can do a pull-request for you to accept it as a branch at least, or merge it if you would like. The code is simple enough, not complicated, and I think it only touched two files (_Dialogs.vue and ScriptEditor.vue)_

**Comment by KlausSchaefers** [comment]
Hi,

yes, I agree the Canvas could use some refactoring. It's not the best code I have written... Please feel free to suggest improvements.

Klaus

**Comment by Equilibrier** [comment]
> yes, I agree the Canvas could use some refactoring. It's not the best code I have written... Please feel free to suggest improvements.

Ok.

**Comment by Equilibrier** [comment]
Implemented this in a forked repo. Did not pushed the changes by pull-request as original QuantUX did not showed interest on this feature.
