### ISSUE TITLE
BUG: an old screen link does not redirect to login page when not authenticated

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#112]
I would expect if I'm copying the link from my quantux working session into another browser, that browser to redirect me to a login-page, as I'm not authenticated in there. Instead if opens the QUX canvas and editing mode, but with zero contents.
It look like a bug to me.

**Comment by Equilibrier** [comment]
The only way to get through this is by clearing the url, to quant-ux.com and relogin and open the screen from the dashboard again.

**Comment by KlausSchaefers** [comment]
Yes, that should not happen....
