### ISSUE TITLE
any super admin features

### ISSUE THREAD

**Issue by karthikindia** [KlausSchaefers/quant-ux#117]
is there any super admin features to manage all users or is there any option to disable signup

**Comment by KlausSchaefers** [comment]
Hi,

you can only manage users directly over mongo :(

For the backend you can disable signups or limit to a certain domain:

https://github.com/KlausSchaefers/qux-java

```json
{
  "user.allowSignUp": false,
}
```

or 

```json
{
  "user.allowedDomains": "my domain.com"
}
```

Does this help?
