### ISSUE TITLE
Where does my project data reside ?!... What is the format of the project data ?

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#118]
It seems in a cloud, since both my local quantUX server and the official quantUX are having the same source-of-truth, regarding my project's data.
I would want (1) to be completely sure my project data is only at my local server, persisted somewhere on the disk, so how do I do that ?!
and (2) what is the format of this project data ? A json ? Some mongodb docs ? I'm asking because I would personally be interested of some sort of subversioning mechanism I could add not necessary to the app itself, but maybe to the entire DB/some json files or so, to work at least in the terminal, for a manual update/revert procedure.

**Comment by KlausSchaefers** [comment]
Hi, the data is in Mongo. The are is  db called MATC and a collection called apps. There you can find all the documents. Each prototype is one document.
