### ISSUE TITLE
BUG: sometimes databinding can crash  ## FIX added

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#119]
The fix is in here (and what I added for the fix) - DataBindingMixin.js -:

![image](https://user-images.githubusercontent.com/106168205/178120354-60b2bdc9-e9d9-4224-8f62-4381a9e946fb.png)

**Now you can fix it yourself in this repo.**

And an optimization would be to also check the isHidden property of the QWidget to also skip the setDataBinding if the widget is hidden, but it seems it's not so easy to access that boolean, since the qWidget propery of the UIWidget is undefined (another bug ?!) and you cannot easily determine that property from css raw style.

_Adding qWidget property of UIWidget would solve the above issue but since I don't know where is the bug in there, a fix I can think of, just for adding that mechanism from scratch, would be to add another appDelta change on the QModel on hide() and show() and interpret that change into the ScriptToModel.js for setting a proper boolean (created) attribute on UIWidget._

**Comment by Equilibrier** [comment]
> Adding qWidget property of UIWidget would solve the above issue but since I don't know where is the bug in there, a fix I can think of, just for adding that mechanism from scratch, would be to add another appDelta change on the QModel on hide() and show() and interpret that change into the ScriptToModel.js for setting a proper boolean (created) attribute on UIWidget.

Actually that didn't worked although I tried one full hour, as the code was simple enough.
This worked, actually, very well, one single change, in UIWidget vue component:
So adding this
![image](https://user-images.githubusercontent.com/106168205/178122508-cb82c17f-63ba-41e6-b502-ac2fc1aaac99.png)

And the code from previous post should be something like this:

![image](https://user-images.githubusercontent.com/106168205/178122520-18c6e25a-d67f-41a8-8e51-7aa195e952e0.png)

**Comment by KlausSchaefers** [comment]
Thx. I will adopt your suggestions
