### ISSUE TITLE
Export as Image gives Error

### ISSUE THREAD

**Issue by bmcgonag** [KlausSchaefers/quant-ux#120]
Running in Docker, is there a limit to the number of items in order to generate an image file?  I get an error when I try to export as an image.

**Comment by KlausSchaefers** [comment]
Hi,

this is most likely related to a bug in the lib that I am using. In general there is no limitation. What I have noticed is that there are some issues when using icons or images. However, I could never really pinpoint the issue down. Could you try a different browser? 

I will try to update the lib. Unfortunately is is discontinued. There are some forks which include bug fixes, but introduce lot's of other bugs :(. The cleanest solution would be to have a separate render server with puppeteer...

**Comment by KlausSchaefers** [comment]
Will move to https://www.npmjs.com/package/html-to-image

**Comment by KlausSchaefers** [comment]
Hi, could you check now?
