### ISSUE TITLE
Screen children lookup code needs an update...

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#126]
Hi,

I think you have some potential bugs on any time you are using the indexOf function on a screen model to search for a certain widget id. It seems !screen!.children have different formats for its ids, like <screen_id>@<widget_id> and when you are using the indexOf(<widget_id>) variant it fails, although the id is indeed in there.
I fixed that on my repo, taking that into account, and it feels good now. I just parsed the second parameter from the <>@<> expression, and replaced all of the indexOf recurrences with this new lookup code and it was good.

I thought you might be interested in providing a fix on here also.
Good luck :) !

**Comment by KlausSchaefers** [comment]
I would have to check this. The @ ids should only happen for master
screens. If there would be a problem in this method, I would expect that
the entire canvas to fail... Let me check still.

Equilibrier ***@***.***> schrieb am Mo., 18. Juli 2022, 14:19:

**Comment by Equilibrier** [comment]
Ok. So it might be cases where this fix is needed, and cases where it is not needed, this is what I understand...
Then, if you have some results, please do share them with me as well, as I personally replaced all of the indexOf recurrences, and it might be wrong.

**Comment by KlausSchaefers** [comment]
I check the code. The scenario that you described should never happen. The simulator uses an "inherited model", where widgets from the parent screens are copied to the child. These copies have an @ in the id, but also the "children" attribute is updated with the id.

I suppose you somehow used the wrong model.

**Comment by Equilibrier** [comment]
The "children" do have the @ delimiter, but not the widgetId which is given to the indexOf function; this was actually the case of the issue. 
It might be something that I wrote that caused this issue, so not present in your repo, but I would not be very sure on that.

One golden questions is: is my fix a "wrong medicine" and there is no "disease" or it can be pure-water-medicine (no side effects), in case you're right ?! In other words, can my fix generate other bugs as well ?
