### ISSUE TITLE
Problem using keyboard return in a logic flow

### ISSUE THREAD

**Issue by pachecoka** [KlausSchaefers/quant-ux#131]
Hey,

I'm having problems while trying to use a text box to trigger a logic flow with the action as being 'keyboard return'.

The scenario is I have a text box, which will receive some user input, and when the user hits the keyboard return it should decide to which screen to go (it's a search input).

The problem is that the keyboard return does not trigger the logic flow. It only gets triggered if I remove focus from the text box (click somewhere else in the screen), click back on the text box and then hit return.

**Comment by KlausSchaefers** [comment]
Hi,

yes this is a bug. Last month I introduced the "Change" trigger as well, which overrules the "Enter" trigger :(. I have fixed it locally, I will deploy it next week. 

As a workaround you might want to try using "Change". This will also trigger on "Enter", but also on blur.

![image](https://user-images.githubusercontent.com/7108416/181710914-6e462fbd-9c62-44da-80cd-53ab1a1ed820.png)

**Comment by KlausSchaefers** [comment]
The fix should be online. Could you check?

**Comment by pachecoka** [comment]
seems to be working, thanks a lot!
