### ISSUE TITLE
reset admin password

### ISSUE THREAD

**Issue by karthikindia** [KlausSchaefers/quant-ux#135]
how to reset admin password from server side
forgot password not working seems some issue in smtp config
any help

**Comment by KlausSchaefers** [comment]
Hi,

1) You will need to configure the mail server properly. Otherwise you cannot send the reset link.

2) When you login with a wrong password, there appears a "reset password" link. Click on the link. You will receive a mail with instructions to enter a new password.

Cheers,

Klaus
