### ISSUE TITLE
Tooltips won't show on overlay screens.

### ISSUE THREAD

**Issue by JanCBrammer** [KlausSchaefers/quant-ux#137]
I place a widget on an overlay-screen. I define a tooltip on that widget. The tooltip doesn't show up when I click through the simulation.

The tooltip *does* show up when the screen is not an overlay.

**Comment by KlausSchaefers** [comment]
Hi, can you test? The fix is online.

**Comment by JanCBrammer** [comment]
@KlausSchaefers, I confirm that it works now. Thanks!
