### ISSUE TITLE
Screen Selection on title

### ISSUE THREAD

**Issue by KlausSchaefers** [KlausSchaefers/quant-ux#141]
The screen (white background) should be only movable only when the title is clicked. Clicking on the background of a screen should not select the entire screen and start moving. This will make the selection of elements inside the screen very difficult. So screens are exceptions, where they can only be moved by clicking on the name/title. If this is not there, one can select multiple elements in a screen by clicking and dragging. All other design tools follow this idea.

**Comment by KlausSchaefers** [comment]
Fixed as optional settings parameter:

![image](https://user-images.githubusercontent.com/7108416/188721477-751f5cdd-0ce9-476a-897c-49f63fa99e59.png)

@adithyaappu: I will consider this for now closed. I have at some point in time change the default behavior.

**Comment by adithyaappu** [comment]
Great. I was away because of some personal and medical issues. I'm back now. Looking to make new contributions. By the way I want to discuss something with you. I can ping you in the QUX email right?

**Comment by KlausSchaefers** [comment]
Yes just drop me a mail.
