### ISSUE TITLE
setProp() not working on widget of type "Label"

### ISSUE THREAD

**Issue by TimBoostGraphics** [KlausSchaefers/quant-ux#154]
Hi,

I might use it wrong or it might not be completed yet (found no documentation for it).
But 
`widget.setProp({label:"test"}) ` 
works for widgets of type "Button" but not for widgets of type "Label"

**Comment by KlausSchaefers** [comment]
Hi,

one workaround for now is to use data mining. Bind the label to a variable, e.g. "textValue". In the script use 

```javascript
data.textValue = 'ABC'
```

I will have a look what happens there.

**Comment by KlausSchaefers** [comment]
Hi, for me it works on Labels but not on Buttons. This is caused due to the way Buttons are rendered.

**Comment by KlausSchaefers** [comment]
Hi, the fix should be online. Can you test. You might to reload the browser

https://user-images.githubusercontent.com/7108416/193920424-80f438c8-6161-4449-8d60-145ad3d4cc01.mov

**Comment by TimBoostGraphics** [comment]
It seems to work fine for every example I use might even have worked before. BUT the setup I was/am using is not working. 

I have screenA with the label called "label", I also have a button on this screen let's call it "buttonA"
"buttonA" on screenA links to screenB when pressed.
On screenB there is another button called "buttonB" when pressed this button links to this script:
`const screen = qux.getScreen('screenA ')
const widget = mainScreen.getWidget("label")

widget.setProp({label:"abc"}) 
return "screenB "`

this doesn't work if I have a label as widget type but it does work for button as widget time, maybe also a rendering issue? There are multiple workarounds but It might cause other issues.

**Comment by KlausSchaefers** [comment]
Hi, this issue lies deeper. It will take some time to fix. In the mean time, data binding could be a good way around the issue.

**Comment by KlausSchaefers** [comment]
I think it is fixed, also for buttons.

**Comment by TimBoostGraphics** [comment]
> I think it is fixed, also for buttons.

Yes it works, Thank you very much!
