### ISSUE TITLE
Distribute Buttons not working in all cases

### ISSUE THREAD

**Issue by KlausSchaefers** [KlausSchaefers/quant-ux#159]
The distribute buttons do not always work as they should

**Comment by adithyaappu** [comment]
I want to add that the  'Press 'D' for distribute' either does not work, or I'm doing it wrong. Same with clone an item.

**Comment by KlausSchaefers** [comment]
https://user-images.githubusercontent.com/7108416/195541081-26605798-5ea8-4bb7-9438-57c900a51b63.mov

**Comment by KlausSchaefers** [comment]
The "algorithm" first groups items into rows / columns. Then it distributes the rows/ columns. 

a) In the columns there is no alignment, this could be better

b) In case there is only one row / column on the move access, this will not work. At least a warning should be shown.

**Comment by adithyaappu** [comment]
I see. This is a little bit counterintuitive. If I have a non distributed set of objects, pressing D won't make any visible change, unless I start dragging the bounding box. This is where I got stuck. Feedback is very important.

**Comment by adithyaappu** [comment]
![cloine distribut](https://user-images.githubusercontent.com/37062841/195561739-22297fdf-49ce-4c39-a880-742cfa63b62b.png)

Is it possible to do it in this flow? If you want I can open a new issue.

**Comment by KlausSchaefers** [comment]
Added some UX improvements. The buttons are only enabled if the distribution is allowed.
