### ISSUE TITLE
I there a way to make a screen as an overlay work when you come from a script?

### ISSUE THREAD

**Issue by TimBoostGraphics** [KlausSchaefers/quant-ux#162]
Hi,

I have a setup where I have multiple screens connected to an overlay screen. The problem is that I need some information about the event widget and screen to change some values on the overlay screen. Unfortunately it doesn't seem to act as an overlay if I go to it from a script, it just renders it as a screen. Is there any way to work around this?

![image](https://user-images.githubusercontent.com/83696957/195546878-8e25fb29-ef9a-4c33-97c2-4c65f0e99aca.png)

**Comment by KlausSchaefers** [comment]
Hi,

this is a bug. If the script returns a string, and there is a screen with the name, it will be rendered as a screen. The simulator
should check if it is an overlay.

As a work around, can you try to wire the script to the overlay? Would it work in this way?

**Comment by TimBoostGraphics** [comment]
How would I get the event through onto the overlay?

**Comment by KlausSchaefers** [comment]
You got store some state in the data. The overview could have a timed
transition to another script to read that. It's quite hack thought 🤔

TimBoostGraphics ***@***.***> schrieb am Do., 13. Okt. 2022,
11:26:

**Comment by KlausSchaefers** [comment]
Hi Tim,

I think I found and fixed the bug. When you return the name of a screen in the script, the Simulator will check if the target is an overlay or screen. Could you verify?

**Comment by TimBoostGraphics** [comment]
> Hi Tim,
> 
> I think I found and fixed the bug. When you return the name of a screen in the script, the Simulator will check if the target is an overlay or screen. Could you verify?

Yes it works, only when returning in the script and not by linking but that is hardly a problem. 
Thank you very much!
