### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by joaopintof** [KlausSchaefers/quant-ux#17]
Hello @KlausSchaefers, all good?

Is there an easy way to prototype the app to be responsive?

tks !!!

**Comment by KlausSchaefers** [comment]
Hi,

for now the prototypes are not responsive. You can however use the https://github.com/KlausSchaefers/vue-low-code project. This will create basically a responsive version of the prototype, but it requires some effort to setup the environment.

I will also check, if I can include the low-code-features better in the editor.

Cheers,

Klaus

**Comment by joaopintof** [comment]
Nice Klaus!
I will try it!

tks!
