### ISSUE TITLE
Import of sketch file not working properly

### ISSUE THREAD

**Issue by rholang** [KlausSchaefers/quant-ux#2]
When I am importing a sketch file into the online ui, then it is importing only a few items. What's the reason for this behavior?

**Comment by KlausSchaefers** [comment]
Hi,

we had for some time a sketch plugin, which stopped working once Sketch moved beyond v 40. I tried to implement an imported that works without a plugin, but this functionality never made it far. The Sketch file format is rather complicated and very incompatible to Quant-UX. I am looking into rewriting the plugin though.

**Comment by 12people** [comment]
@KlausSchaefers Why was this closed? Will it not be implemented? And if not, why not?

**Comment by KlausSchaefers** [comment]
Writing sketch plugins is quite complex. I don't have the time to do that now. I was experimenting with writing a Sketch renderer from scratch (https://github.com/KlausSchaefers/quant-ux/blob/master/src/unit/SketchTest.vue), but the file format is not well documented. So it requires a lot of reverse engineering.
I am working no on an Figma import. This seems pretty straight forward. There should be a first version online within the next weeks.

**Comment by 12people** [comment]
The format seems to be fully documented at https://github.com/sketch-hq/sketch-file-format . Or is something missing from that repo?
Figma import sounds great! :)

**Comment by KlausSchaefers** [comment]
No, it's more about how vectors are rendered... It's from my understanding not SVG but something custom. That makes it difficult. Also, I am not sure if I could 100% recreate all the rendering. Figma on the other hand, makes it quite easy to get PNGs for complex shapes.
