### ISSUE TITLE
how fix 10 error

### ISSUE THREAD

**Issue by khanhnam99** [KlausSchaefers/quant-ux#21]
pls, how fix them

![image](https://user-images.githubusercontent.com/575720/100415747-7416e680-30af-11eb-8d8b-c3cc4fe39ddd.png)

![image](https://user-images.githubusercontent.com/575720/100415797-8ee95b00-30af-11eb-957e-b26acc38887a.png)

![image](https://user-images.githubusercontent.com/575720/100415842-a58fb200-30af-11eb-9dc0-87db73a9e342.png)

**Comment by KlausSchaefers** [comment]
Hi,

can you do the following:

1) Delete node_modules folder

2) delete package-lock.json

3) run "npm install"
