### ISSUE TITLE
Setup with OAuth Provider

### ISSUE THREAD

**Issue by lexermal** [KlausSchaefers/quant-ux#210]
Hello Klaus,

Your project is awesome! I used it to create a lot of mockups for my projects. 

Last year I set up your project on my Kubernetes cluster and it's still running smoothly. I'm planning to contribute the deployment charts. 

Before that, I would like to update them. I noticed you added new environment variables for authentication. I would like to make it work with the OAuth2/SAML Provider Authentik. Do you have any idea what settings need to be set? 
These are the endpoints it has https://goauthentik.io/docs/providers/oauth2/

Thanks in advance!

**Comment by KlausSchaefers** [comment]
Hi,

Quant-UX currently supports it's own IAM and Keycloak. I don't know Authentik, but I assume the API's will be similar to KeyCloak. I am not sure if they are 100% compatible though. My best guess is, that one has to implement some custom function to integrate with Authentik. This would basically include two mayor changes:

1) In the front-end one needs to implement a new AuthenikService with the same methods as [UserService](https://github.com/KlausSchaefers/quant-ux/blob/master/src/services/UserService.js). The [Services](https://github.com/KlausSchaefers/quant-ux/blob/master/src/services/Services.js) factory also needs to be updated

```js
    getUserService () {
        if (this.config.auth === 'keycloak') {
            return AuthenikService // the new service
        } else if (this.config.auth === 'keycloak') {
            return KeyCloakService
        } else {
            UserService.setToken(UserService.getToken())
            return UserService   
        }
    }
```

b) On the backend one needs also a custom implementation, e.g. to validate tokens. This service should download the certificates from Authentik and use the to validate the token, very much like the [KeyCloakTokenService](https://github.com/KlausSchaefers/qux-java/blob/master/src/main/java/com/qux/auth/KeyCloakTokenService.java) does. The Mac.java file decides based in the config which ITokenService to produce.

The following picture shows how the auth in the UI and backend are linked:

![QUX Architecture](https://user-images.githubusercontent.com/7108416/210779877-2f624e89-bb8b-4253-8b03-6f97458a6676.png)

If Authentik is 100% compatible with Keycloak one just needs to update the config, namely

```js
 "auth.service": "keycloak",
    "auth.keycloak.server": "http://localhost:8180",
    "auth.keycloak.realm":"myrealm",
    "auth.keycloak.claim.lastname":"",
    "auth.keycloak.claim.role": "",
    "auth.keycloak.issue": "",
    "auth.keycloak.claim.email": "",
    "auth.keycloak.claim.name": ""

```

Does this help?
