### ISSUE TITLE
Vertical alignment "top" breaks horizontal alignment

### ISSUE THREAD

**Issue by TBG-FR** [KlausSchaefers/quant-ux#215]
### Description

When setting a `top` vertical alignment on an element (text, MUI label, MUI H3, etc), the horizontal alignment of this item is ignored or cleared (the item is then aligned to the `left`)

### How to reproduce

1. Create a new text, or add a Widget (label, H3, etc)
2. Set its horizontal alignment to `center`
3. Set its vertical alignment to `bottom` -> Everything is working well ✅ 
4. Set its vertical alignment to `top` -> The item is now left aligned 🔴 

### Screenshots

Horizontal align `center` + Vertical align `bottom` ✅ 
![image](https://user-images.githubusercontent.com/18146038/212481305-71825a7f-d032-4819-9eef-4815ea99faac.png)

Horizontal align `center` + Vertical align `top` 🔴 
![image](https://user-images.githubusercontent.com/18146038/212481315-9404357e-8c43-4cc9-96e3-791d9ec309ac.png)

**Comment by KlausSchaefers** [comment]
Thanks for letting me know. I will try to fix it in the next days.

**Comment by KlausSchaefers** [comment]
https://user-images.githubusercontent.com/7108416/212767559-edebab88-a1d9-4c2a-bfb6-d339a4fe10ab.mp4

**Comment by KlausSchaefers** [comment]
Should be fixed,, if you could confirm.

**Comment by TBG-FR** [comment]
Fixed it is ! Thank you for your reactivity 🌞
