### ISSUE TITLE
Text wrapping related

### ISSUE THREAD

**Issue by adithyaappu** [KlausSchaefers/quant-ux#224]
![text wrapping](https://user-images.githubusercontent.com/37062841/215392648-e25e91a1-e10f-4842-8f4d-e502023dccae.gif)

So I have noticed this behaviour, which is quite annoying. I can't pin point the reason. But one scenario I noticed is that, if there is an additional blank line in the text box this wrapping happens most of the times. In this case I'm using the paragraph widget available. it causes the same issue, but there is no additional space or line at the end.

**Comment by KlausSchaefers** [comment]
What kind of browser - plugin do you have there? It might interfere with the copy paste...

**Comment by KlausSchaefers** [comment]
I think I fixed... Could you check?
