### ISSUE TITLE
Gradient Slider not switching

### ISSUE THREAD

**Issue by adithyaappu** [KlausSchaefers/quant-ux#225]
![gradient issue](https://user-images.githubusercontent.com/37062841/215394373-74318bbd-0095-4d62-9135-12458a9f71f7.gif)

A common use case with gradient slider is switching the sides of the existing two colours. This is generally used because it is difficult to individually change colours. Also some times switching the sides is all  needed to do.

I think the solution is identify first colour as Colour 1 and last colour as Colour two, instead of assigning it to specific slider.

**Comment by KlausSchaefers** [comment]
Thanks!
