### ISSUE TITLE
Changing Data Binding rule type does not update drop down boxes.

### ISSUE THREAD

**Issue by adithyaappu** [KlausSchaefers/quant-ux#236]
![data binding issue](https://user-images.githubusercontent.com/37062841/218677977-ec518364-a6dd-4eeb-829d-e0b10c390819.gif)

So I'm not sure whether I'm understanding this correctly. Here I have set a Rule Type for a logic operator, with 'Widgets'. It is already applied. Now, I want to change it to 'Data Binding'. When I do that, the first drop down changes, so that I can select the variable, but the second and third drop down remains as such, means it still carries the options of the 'Widgets' Rule Type. I had to remove and redo the link to get it back. 

Checked on:
Firefox 109.0.1
Edge 110.0.1587.41

**Comment by KlausSchaefers** [comment]
Yes, there was a bug. When the type is changed from widget to data binding not everything is deleted.
