### ISSUE TITLE
No photos -  Record a Task flow

### ISSUE THREAD

**Issue by uki150** [KlausSchaefers/quant-ux#24]
Photos don't load when I try to create a flow. I'm getting a 404 error. The photo link looks incomplete.

**Comment by KlausSchaefers** [comment]
Thanks for noticing. I will fix ASAP

**Comment by KlausSchaefers** [comment]
Hi, I think I fixed it. Can you retry (potentially force a reload in the browser)

**Comment by uki150** [comment]
It works! Thanks!
