### ISSUE TITLE
[Enhancement Request] - Add dropper tool to Color selectors so I can match colors of screen-shots i'm working with.

### ISSUE THREAD

**Issue by bmcgonag** [KlausSchaefers/quant-ux#245]
As a user I'd like to have a dropper tool added to the color selector tools in Quant-UX so I can more accurately match colors in screenshots I'm working with and make the mock-ups more seamless, and avoid inadvertent color mismatches.

I don't know a better name for this tool, but it's essentially an icon that when clicked allows you to then click on a color anywhere on the screen to get the hex / rgb codes and auto-fill them in the color selector.

**Comment by KlausSchaefers** [comment]
![image](https://user-images.githubusercontent.com/7108416/225937869-17d78dd0-cf81-4501-84d4-cff9ef5372d2.png)

Like this?
