### ISSUE TITLE
Sticky ruler - does not work

### ISSUE THREAD

**Issue by uki150** [KlausSchaefers/quant-ux#25]
By setting up lines and selecting "Sticky ruler", my header is not stuck to the top of the page as I scroll the page.

**Comment by KlausSchaefers** [comment]
Sticky ruler means that 'attached' items will be moved when the ruler is moved.

https://user-images.githubusercontent.com/7108416/103640451-f4025d00-4f47-11eb-9670-e2f847b51323.mp4
