### ISSUE TITLE
Unable to use image as a segment

### ISSUE THREAD

**Issue by adithyaappu** [KlausSchaefers/quant-ux#254]
I imported an image into QUX, then specified that screen as a segment. 

![image](https://github.com/KlausSchaefers/quant-ux/assets/37062841/3f28dd17-3661-4139-a08e-254f87e9a1a1)

I can see the preview, but when imported, only a blank screen is shown.

![image](https://github.com/KlausSchaefers/quant-ux/assets/37062841/757b137f-1507-4f09-8e1f-817cf8811532)

**Comment by adithyaappu** [comment]
found one thing related. The screen segment is shown as 'Hidden' in Layers panel. I'm unable to change the state
![CopyQ rZoUDi](https://github.com/KlausSchaefers/quant-ux/assets/37062841/365f3294-26e0-4235-9d0c-45b75146a54a)

**Comment by KlausSchaefers** [comment]
Does it appear after a reload (or double click on the canvas)?

**Comment by adithyaappu** [comment]
No. 

Browser check also done,
NOT working in both Firefox and Edge
