### ISSUE TITLE
Design GPT (Beta) - Issue on self-hosted docker

### ISSUE THREAD

**Issue by CyberTechArmor** [KlausSchaefers/quant-ux#256]
Hello, I have to start out by saying Quant-UX is fantastic and I thoroughly enjoy using it. I checked open issues with the terms: openai, ai, chat, and Design GPT with zero results for all.

**Issue:**
There is an error when using Design GPT (Beta), where when you submit it says "something went wrong on the server" and does not generate anything.

**Setup:**
I am running Quant-UX with docker and exposed to the internet. I am able to login, use, and share.

**Qualified:**
I have tested my openai api key with the Quant-UX official website, and it works perfectly there.

This is a very interesting feature, and I would really enjoy being able to use on my own instance of Quant-UX. I would be happy to look through the code, but I am no expert and I'm not sure where to look. I would be happy to provide more information or help in any other way I can.

Thank you for this amazing piece of software!

**Comment by KlausSchaefers** [comment]
Hi,

thanks for notifying me. Could you check:

1) The developer console and see if there is an error?

2) The java container should have logs, most likely on the console. Is there an error?

Kind Regars,

Klaus

**Comment by KlausSchaefers** [comment]
The OpenAI proxy was not pushed to the repo. I just did. In some moments there should be a new docker image. Could you test with that?

**Comment by CyberTechArmor** [comment]
That's fantastic! I will try to test before I leave, otherwise I will try in a few hours (once I'm back).

**Comment by CyberTechArmor** [comment]
It works! I tested with a wrong api key and it reported "wrong api" which is nice, and I applied the correct api key and it worked perfectly. Thank you very much for the quick response.

**Comment by codingnooob** [comment]
Hi @KlausSchaefers,
I am having the same issue, except it doesn't work on the site for me either.
