### ISSUE TITLE
Function to collapse all opened group on the layers panel

### ISSUE THREAD

**Issue by joey542** [KlausSchaefers/quant-ux#268]
It could be a really useful function when someone working with many groups. Especially when open the project, all groups are opened default. It is really confusing.
![image](https://github.com/KlausSchaefers/quant-ux/assets/30594454/c720a6e5-cea3-4468-8900-af329f5cf460)

**Comment by KlausSchaefers** [comment]
Good idea. I changed it in the next release. You can try out here https://dev.quant-ux.com/
