### ISSUE TITLE
npm install failed -  'cssstyle@2.2.0' is not in the npm registry.

### ISSUE THREAD

**Issue by EllamOndre** [KlausSchaefers/quant-ux#27]
![image](https://user-images.githubusercontent.com/77210948/104108095-3918ed00-52c2-11eb-821e-28af4566dd27.png)

**Comment by KlausSchaefers** [comment]
I will take a look what is wrong...

**Comment by KlausSchaefers** [comment]
can you delete the package-lock.json and try again?

**Comment by EllamOndre** [comment]
Thanks for the reply. I know it's not your fault, but a problem in the dependencies chain. I deleted the package-lock.json file and tried again. Unfortunately I ran into another problem during installation, as shown in the screenshot.
Please, don't spend too much time solving the problem - I tried to use your product during my research, but it's not mandatory to be able to.
Have nice days :)
![image](https://user-images.githubusercontent.com/77210948/107248363-83f96200-6a32-11eb-9712-e474e738fe88.png)

**Comment by KlausSchaefers** [comment]
What are you trying to accomplish? I the only version good enough?

**Comment by EllamOndre** [comment]
I wanted to try using Quant-ux as suggested by Vue-Low-Code. I would apply what you so well explain in the description of this latter project developed by you. I abandoned the idea when I wasn't able to install Quant-ux  :(

**Comment by KlausSchaefers** [comment]
You do not have to install Quant-UX locally. You can design in the cloud hosted version and link through the share token.

**Comment by EllamOndre** [comment]
Oh thank you for the hint. I don't love to work in the cloud, due to unstable internet connection. But I will try it.
I very appreciate your wonderful work.

**Comment by j2l** [comment]
I have the same problem and wonder how to run "quant-ux" (https://youtu.be/srGVFX_he8E?t=154) if I don't `npm i -g quant-ux`
Or do you have a new share mechanism?
BTW, great great project :)

**Comment by KlausSchaefersAtWork** [comment]
Hi,

which repo did you clone? This one? Or does the error happen if you run the CLI?

**Comment by KlausSchaefersAtWork** [comment]
You cab also take a look at https://github.com/KlausSchaefers/vue-low-code. This is a new alternative to the CLI. It only needs the CLI to productize the project. You can clone this example: https://github.com/KlausSchaefers/vue-low-code-example
