### ISSUE TITLE
is there an SVG widget?

### ISSUE THREAD

**Issue by rozek** [KlausSchaefers/quant-ux#274]
The title pretty much says it all: is there a widget to display SVG documents?

**Comment by KlausSchaefers** [comment]
yes

**Comment by rozek** [comment]
well, but the question is "where"? However, I learned from other responses that we seem to have different sets of widgets.

Hence, the question should perhaps better be: "where do I get an SVG widget"?

**Comment by KlausSchaefers** [comment]
Ah. Sorry. I thought it was about the data image. Create a vector drawing.
That will create the widget.

Andreas Rozek ***@***.***> schrieb am Sa., 23. März 2024,
17:03:
