### ISSUE TITLE
Please provide "readonly" option for input controls

### ISSUE THREAD

**Issue by rozek** [KlausSchaefers/quant-ux#277]
"Text" widgets do not support data bindings - but input widgets do.

Could you please provide a "readonly" property for input widgets, e.g., to implement dynamic (text, date, time, etc.) displays?

Thanks in advance for your effort!

**Comment by KlausSchaefers** [comment]
Labels can have a data binding:

1) Create a label

2) Select the label

3) Select the "prototype " tab

4) Click "Add databinding"

![image](https://github.com/KlausSchaefers/quant-ux/assets/7108416/9befa703-ad4c-46ee-81ae-8277d8a112a2)

**Comment by KlausSchaefers** [comment]
One can't disable elements. Just design them as normal rectangles.
