### ISSUE TITLE
problems with web service

### ISSUE THREAD

**Issue by rozek** [KlausSchaefers/quant-ux#278]
I am using the Docker-based installation as described in the docs...

...but I can't get the "Web Services" working.

When configuring a "Get" with a well-known URL (e.g., "https://www.spiegel.de") and pressing "Test", I just get the error "something went wrong" and the browser console says:

Access to fetch at 'https://www.spiegel.de/' from origin 'http://localhost:8082' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Where do I have to configure the policies in the Docker file in order to get web services working?

**Comment by KlausSchaefers** [comment]
Spiegel does not allow "Cross Origin Requests". This means the website can be only loaded within the original browser window that has the right domain associated. The same is true for IFrames. This is a common mechanism to prevent fraud, phishing and protect content. 
You need a proxy server to bypass the CORS header issue.
