### ISSUE TITLE
Ctrl-scroll zoom uses reversed directions

### ISSUE THREAD

**Issue by jancborchardt** [KlausSchaefers/quant-ux#28]
(For clarification on the scroll down and up: I have natural scrolling enabled on the mouse wheel. When disabling it, it inverts for every app listed below including Quant, still making it the odd one out.)

The common standard among apps / platforms seems to be <kbd>Ctrl</kbd> + scroll down to zoom _in_ (that is, make the image larger). This works with e.g.: Inkscape, Penpot, Google Maps (there without Ctrl as they use scrolling for zooming), and to zoom any sort of website generally.

In Quant, this direction seems to be reversed: <kbd>Ctrl</kbd> + scroll down zooms out, and <kbd>Ctrl</kbd> + scroll up zooms in, which is quite unexpected.

**Comment by jancborchardt** [comment]
To fix it, I’m guessing the `onZoomMinus` and `onZoomPlus` in the block at https://github.com/KlausSchaefers/quant-ux/blob/master/src/canvas/Zoom.vue#L108-L112 would have to be switched around. :)

**Comment by jancborchardt** [comment]
Fix tested locally and works, pull request at https://github.com/KlausSchaefers/quant-ux/pull/29 :)

**Comment by KlausSchaefers** [comment]
Hi,

I just tried on my branch it works like as you described. CNTR and DOWN zooms out... I have to check on another machine. What OS are you using?

**Comment by KlausSchaefers** [comment]
I check with natural scrolling (Mac OS) on and off. Quant-UX works like Figma and Google Maps. With reverse the zoom direct, but all are in sync. So if I:

1) have natural scrolling switched on

2) CNTRL + Move the finger from back of the mouse to the top ( scroll down)

3) Quant-UX, Figma & Maps zoom out (the image get's smaller)

**Comment by KlausSchaefers** [comment]
Hello Jan,

I think I found the issue. Firefox returns the inverse scroll direction. I assume you are using FireFox?

**Comment by KlausSchaefers** [comment]
I created a pull request with the FF fix? Could you please test?

**Comment by KlausSchaefers** [comment]
Fix is online

**Comment by jancborchardt** [comment]
Sorry for the late reply @KlausSchaefers! Indeed I use Firefox and the fix does work – thanks a lot! :)
