### ISSUE TITLE
Docker and Nginx Server Setup - Base Route

### ISSUE THREAD

**Issue by Bonfims** [KlausSchaefers/quant-ux#293]
Hey, you guys did a wonderful job on this project.

May I suggest trying to put projects into a `base route` or `base path` approach, then we can have better options with NGINX reverse proxy without creating a server per "quant service".

I'm trying to put "qux-fe", "qux-be" and "qux-ws" on the same NGINX server, same domain and same SLL certificate, but I can't, all project routes are based on the root path and I'm being forced to have a server for ws.domain.com, fe.domain.com and be.domain.com to proxy them all.

With "base route" approuch we can combine all projects with "location" instructions, like: 

```
#  ... Same SSL and Domain

# Front end
location /quant-ux {
    ...
    proxy http://quant-fe;
}

# Back end
location /quant-api {
    ...
    proxy http://quant-be;
}

# Websocket
location /quant-ws {
    ...
    proxy http://quant-ws;
}
```

what do you think?

**Comment by KlausSchaefers** [comment]
Yes, on the production server I do basically the same. For the websocket you need some special NGINX conf. Something like:

```
server {

   root /usr/share/nginx/html;
   index index.html index.htm;

   server_name ws.server.com;

    location / {

                proxy_set_header        Host $host;
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
                proxy_pass              http://quant-ws;
                proxy_set_header        Upgrade $http_upgrade;
                proxy_set_header        Connection "Upgrade";
                proxy_http_version 1.1;
                proxy_read_timeout  90;
    }

}
```

**Comment by KlausSchaefers** [comment]
These ones should be the important VARs

```
const proxyUrl = process.env.QUX_PROXY_URL || 'https://v1.quant-ux.com'
const wsUrl = process.env.QUX_WS_URL || 'wss://ws.quant-ux.com'
```

**Comment by Bonfims** [comment]
> These ones should be the important VARs
> 
> ```
> const proxyUrl = process.env.QUX_PROXY_URL || 'https://v1.quant-ux.com'
> const wsUrl = process.env.QUX_WS_URL || 'wss://ws.quant-ux.com'
> ```

Thank you for quick reply!

So, if i use them like below, will work too?

 ```
QUX_PROXY_URL=https://quant-ux.com/v1
QUX_WS_URL=wss://quant-ux.com/ws
```
With a reverse proxy i can redirect `/ws` to websocket server and `/v1` to front end server, using same domain, its true?

**Comment by KlausSchaefers** [comment]
Hi,

- The proxy should work. Maybe you have to tweak path rewriting in nginx. 
- It should be your server. With the websocket you have to test how the proxy routing works, maybe also path rewriting is required.
