### ISSUE TITLE
Handle browser previous page action

### ISSUE THREAD

**Issue by baudev** [KlausSchaefers/quant-ux#297]
Hello, 

I've checked the existing issues and I can't find any on this subject:
is it possible to manage the case of backtracking in the browser history?

Typically, when a user uses the demo on his phone, he may be tempted to go back to the previous page using browser action (especially with gesture navigation).

If this function doesn't exist, I understand that it's probably not easy to implement.

Thanks in any case for this great tool!

**Comment by KlausSchaefers** [comment]
This works on my phone. Can you try this?

https://app.quant-ux.com/#/test.html?h=a2aa10are2zD5a06aNlVDuI8hEBbegxkBtmpdihbK3hwSKuXEIHctain41ZC&ln=en

**Comment by KlausSchaefers** [comment]
Ah, but not on desktop. I will fix

**Comment by baudev** [comment]
Thanks for your quick answer.
It seems to work (but not always). I'll try to understand when to reproduce the bug.
