### ISSUE TITLE
Is the server opensource?

### ISSUE THREAD

**Issue by jianzhichun** [KlausSchaefers/quant-ux#3]

**Comment by KlausSchaefersAtWork** [comment]
Hi, currently not. The code still needs to be prepared to be open sourced.

**Comment by KlausSchaefers** [comment]
Hi, no. The server still contains proprietary code that I need to be factored out. Still didn't find any time to do this.

**Comment by jianzhichun** [comment]
Does quant-ux support internationalization?

**Comment by KlausSchaefers** [comment]
Yes!

**Comment by jianzhichun** [comment]
@KlausSchaefers How to change language?

**Comment by KlausSchaefers** [comment]
Hi,

1) currently there is only english, so there is no need to change the language.  Once there is a another language, one can enable language switching

2) Yes, Why?

**Comment by jianzhichun** [comment]
@KlausSchaefers
1. I want a Chinese version.
2. It's too slow beacuse of the [GWF](https://en.wikipedia.org/wiki/Great_Firewall). Eh, I mean I will wait for the opensource of server.

**Comment by KlausSchaefers** [comment]
Hi,

1) would you be willing to contribute the Chinese translation? 

2) I will focus my efforts now on building a desktop version based on electron. Would this be a solution for you?  The open source release of the server might still take some time...

**Comment by jianzhichun** [comment]
1. I will, but I work in alibaba-inc and it's a [996](https://github.com/996icu/996.ICU) schedule, so maybe I also cannot find enough time.
2. Does the desktop version need access your server?

**Comment by KlausSchaefers** [comment]
Hi,

no that idea is to make it work without the server. 

I will keep you in the loop.

Klaus

**Comment by jianzhichun** [comment]
Ok. Thx

**Comment by KlausSchaefers** [comment]
Hi, please checkout https://github.com/KlausSchaefers/qux-java

**Comment by jianzhichun** [comment]
@KlausSchaefers I have made it work with localhost devServer proxy yesterday, the code is beautiful.
![image](https://user-images.githubusercontent.com/17561654/82959113-90937280-9fe9-11ea-9e4f-b30bbb36a458.png)
But I also encountered some problems.
1. I have to add max.users option to make backend work.
![image](https://user-images.githubusercontent.com/17561654/82959219-c7698880-9fe9-11ea-92d7-8673236848b0.png)
2. When server starting, there is a VertxException warning log.
![image](https://user-images.githubusercontent.com/17561654/82959299-fb44ae00-9fe9-11ea-881a-ac04fe01d59a.png)
![image](https://user-images.githubusercontent.com/17561654/82959341-0ef01480-9fea-11ea-8247-fbb3b9f74681.png)

**Comment by KlausSchaefers** [comment]
Hi,

great that you got it working!

I thought I had removed the "max.uxers"... Strange. The test cases do do not fail or? I will check later. 

The thread blocking is caused because during server boot I read some files using the blocking FileAPI. This can take some time, because VERTX, when started from the far-jar, copies all files into a temp folder. Also, disk speed can contribute to the issue. As this happens only once during server start, it is not a big issue. One could made the code async, or put it in a blocking call.

Could you in the future raise issues in the qux-java repo? THX!

**Comment by KlausSchaefers** [comment]
Check the latest commit. The max.users should have been removed.

**Comment by jianzhichun** [comment]
Ok

**Comment by KlausSchaefers** [comment]
I added some code to load the mail templates blocking, please check of this help.

**Comment by jianzhichun** [comment]
Yes, it helps. 👍👍👍
