### ISSUE TITLE
Exposing APIs

### ISSUE THREAD

**Issue by JNdhlovu** [KlausSchaefers/quant-ux#30]
First of all awesome work on this. I can see the data is all transmitted to  https://v1.quant-ux.com, if I need this data is there any way of exporting/exposing it?

I would like to extend the functionality to include exposing designs via an API which I can then parse on clients.

**Comment by KlausSchaefers** [comment]
Hi,

The backend repo is this one: https://github.com/KlausSchaefers/qux-java. You can clone it and run your own server. There is already an API to 'expose' designs. You need a share token (Canvas > Menu > Share>Code Generation). With this token you can download the design and the images. The endpoints are:

JSON: `${this.server}/rest/invitation/${token}/app.json`

IMAGES: `${this.server}/rest/images/${token}/${style.backgroundImage.url}`


You can find all the endpoints listed here: https://github.com/KlausSchaefers/quant-ux/blob/master/src/services/ModelService.js

The file format is explained here:

https://github.com/KlausSchaefers/quant-ux/blob/master/docs/file-format.md

The quant-ux format is 'flat' If you need a (render) -tree model, take a look at 
https://github.com/KlausSchaefers/vue-low-code/blob/master/src/qux/transformer/Flat2Tree.js

Hope this helps. What do you want to do?

Cheers,

Klaus

**Comment by JNdhlovu** [comment]
Thank you so much,really appreciate the work and prompt response

**Comment by KlausSchaefers** [comment]
If you need more help, do not hesitate to contact me.
