### ISSUE TITLE
Feature request : Render external URL / iFrame and do A/B test, track the analytics / heatmap ?

### ISSUE THREAD

**Issue by antoninadert** [KlausSchaefers/quant-ux#304]
First, thanks for making quant-ux, it is a wonderful vision and has the potential to revolutionize UX research.

This is a follow-up of this issue : https://github.com/KlausSchaefers/quant-ux/issues/273

This issue is about evaluating the feasibility of doing user testing and analytics on a set of external URL instead of using the Quant-UX included prototyping tool.

The use case is : there is a website already in production, we would like to test it with the same analytics / heatmap / A/B testing tools that Quant-UX provides, but we would like to use the real website directly.

That would allow us 2 things : 
- No need to prototype what is already developed, we directly test and analyze
- We can use complex interactions and data which are usually hard to prototype, since it is already developed

I wonder if there would be a trivial path forward that you can think of (even with limitations), or if it seems this development is just too distant to the current architecture to be ever done one day. 

Many thanks for reflecting on this issue.

**Comment by KlausSchaefers** [comment]
This will not work on sites that have do not allow CORS, which is the case for most websites. Also, if the page changes, all heatmaps etc would be useless.
