### ISSUE TITLE
Question about user notification

### ISSUE THREAD

**Issue by eugeneym** [KlausSchaefers/quant-ux#306]
Hello!
I'm using the version of the QuantUX deployed with docker-compose. But I have a problem with sending notifications
If I use QUX authentication, the notifications work. But as soon as I use keylock authentication, no notifications are sent.

> quant-ux-backend           | 15:35:39.097 [vert.x-eventloop-thread-0] ERROR com.qux.rest.UserREST - insertExternal() > Created user
> quant-ux-backend           | 15:35:39.501 [vert.x-eventloop-thread-0] ERROR com.qux.bus.MailHandler - handle() > from: quantuxmail@mycompany-nt >> to : [alex.smith] >> subject : Welcome to Quant-UX >> txt: Hello,
> quant-ux-backend           |
> quant-ux-backend           | thank you for registering at Quant-UX. You can now login at https://quantux.mycompany.int
> quant-ux-backend           |
> quant-ux-backend           |
> quant-ux-backend           | Best Regards,
> quant-ux-backend           |
> quant-ux-backend           | Your Quant-UX Team
> quant-ux-backend           |
> quant-ux-backend           | 15:35:39.501 [vert.x-eventloop-thread-0] ERROR com.qux.bus.MailHandler - handle() > Could not send mail to alex.smith
> quant-ux-backend           | 15:35:39.502 [vert.x-eventloop-thread-0] ERROR com.qux.bus.MailHandler - handle() > error:
> quant-ux-backend           | java.lang.IllegalArgumentException: invalid email address

It seems that instead of email, the message is trying to send to a username..
Fields are mapped into keylock from the active directory correctly.
Maybe I should add a QUX_KEY_CLOAK_CLAIM_EMAIL variable, but I have no idea what its value should be. 
I would be grateful for any hints.

**Comment by KlausSchaefers** [comment]
Hi, sorry for the late reply. The `QUX_KEY_CLOAK_CLAIM_EMAIL` will determine which field from the token Quant-UX receives from Keycloak contains the email address. This is usually defined in the Keycloak Realm config somewhere. But I have no idea how this works with active directory
