### ISSUE TITLE
White screen on "Share and Comment" link

### ISSUE THREAD

**Issue by TBG-FR** [KlausSchaefers/quant-ux#315]
# Describe the bug

Using the "Share this app" menu, the link provided to share the prototype and allow people to add comments on it doesn't work at all

### To Reproduce

_Steps to reproduce the behavior:_

1. Create a new projet (also tried with an old existing one, just to be sure)
2. Add some design elements
3. Go back to the prototype and hit the sharing button
4. Try to use the `Test` link (it works ✅)
5. Try to use the `Share and Comment` link (it show a fully white screen 🛑 )

### Expected behavior

It should be possible to view and comment the prototype, as it was before

# Screenshots

No screenshots but here are the links
- Test : https://app.quant-ux.com/#/test.html?h=a2aa10aBVndg8kZCQbx3vS9GBW4EuFRaQBip29H5N9ubtAqWDuxkypabrEp6&ln=en
- Share : https://app.quant-ux.com/#/share.html?h=a2aa10aBVndg8kZCQbx3vS9GBW4EuFRaQBip29H5N9ubtAqWDuxkypabrEp6

# Context

### Browser

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Extra

Additional Context: Also tried in private navigation to exclude any caching issue... (and in both cases **no error at all displayed in the console**)
Temporary workarounds, if any: N/A

**Comment by KlausSchaefers** [comment]
Fixed, can you please test

**Comment by TBG-FR** [comment]
It works well now, good job 😉
