### ISSUE TITLE
Restore method binding in the UI please

### ISSUE THREAD

**Issue by lcuevastodoit** [KlausSchaefers/quant-ux#319]
Hi Klaus, If you don't have any technical problems or bugs with that, it would be great to put it back the method binding in the UI because it's easier for the Quant-ux user who doesn't know much about development to relate the widgets actions with custom methods on Luisa's side. I think that this function should be recovered.
Thanks in advance

#318

**Comment by KlausSchaefers** [comment]
Should be back in the "Prototype view"

**Comment by KlausSchaefers** [comment]
![image](https://github.com/user-attachments/assets/947aaac5-2168-4b4d-bd86-51ce6d0a8228)
