### ISSUE TITLE
Can't change width and height of screen

### ISSUE THREAD

**Issue by j2l** [KlausSchaefers/quant-ux#32]
I'd like a landscape screen among my portrait ones

![image](https://user-images.githubusercontent.com/65325/108916930-40f0de80-762f-11eb-9d19-4500edb262b8.png)
width doesn't respond at all
height can be changed but is not applied

**Comment by KlausSchaefers** [comment]
Hi,

you set the screen size before you create the prototype for a given device. You cannot change after. You can only make the screens longer. Otherwise one would get horizontal scrolling in the simulator.

You can change the screen size and width for all screens in the menu.

**Comment by j2l** [comment]
Thank you Klaus!
There's no way to rotate the screen? 
How to show the responsive design?
BTW, I could import landscape screens from Figma but I didn't find how to modify navigation elements.

**Comment by KlausSchaefers** [comment]
Hi,

doing responsive designs in a tool is tricky (Figma also does not support this). What you can do is use the "Constraints" to specify how certain element should behave, e.g. if their width should grow or not. In the "Data & Code" view you can also define wrapping for child widgets. Please note that these properties are only used in vue-low-code and not the simulator. 

The best solution is to design separate prototypes for different resolutions.

Cheers,

Klaus

**Comment by j2l** [comment]
Ah well, ok then. 
Thank you

**Comment by KlausSchaefers** [comment]
What do you want to build. I can help you a little. This is also a good chance for me to learn.

**Comment by j2l** [comment]
Wow, thank you! I really appreciate :smile_cat: 
On QuantUX, it's 603577fd295894053a55a295, I don't know if it's hosted on your side or mine.

I'm a student in cinema and I develop an interface to show some video service:
![image](https://user-images.githubusercontent.com/65325/109148671-d93daf00-7766-11eb-87c8-1d0922858690.png)

The screen on the right should also be available in landscape mode (to fit the movie). Best would be to animate the screen rotation, but it's not mandatory.

Additionally, as you can see, I imported "Firefox Browser UI Kit (Community)" from Figma community to show a browser.
But I can't access the top and lower bar that should be fixed on top and bottom of the screen. Basically, my Figma import looks like a screenshot applied to the screen, so scrolling also scrolls top and bottom bars which is not correct.

Finally, since I can't export to node-red+uibuilder+vue, I'd LOVE to be able to export widgets as simple vue (template+script) of each screen from QuantUX, not just vue-low-code since node-red will take care of routes and business logic.
![image](https://user-images.githubusercontent.com/65325/109149375-c2e42300-7767-11eb-8b51-760f1c926e84.png)

Maybe, one thing at a time :smile: 

Thank you again for your kindness

**Comment by KlausSchaefers** [comment]
Hi,

so I understood correctly that you imported from Figma? In this case, the design is indeed just a bitmap export. This would not work with vue low code. If you do not want to rebuild the UI in Quant-UX, you can stay with Figma and use figma-low-code. 

There is a way to make Figma-low-code work as a responsive app. It is not documented, and I am not sure if it works with rotation. Let me check and come back to you.

Why do you want to integrate with Node-Red? Would it be an option to host the low-code stuff as a standalone server, and use and Iframe to show the content?

Klaus

**Comment by j2l** [comment]
Only the browser screens on the right (background) are Figma, all the rest is QuantUX (wireframe style)
I prefer QuantUX to Figma for its widgets :smile: and quick prototyping.
Figma is very good for creative work so I thought importing a browser render would help in this case.

Node-Red can generate routes from OpenAPI, manage sockets (and a ton of other services) and can include any NPM library. So you can prototype any service.
It's very convenient to visually see your routes to help you debug.
For example, here's a screenshot of what I'm working on, obvious:
![image](https://user-images.githubusercontent.com/65325/109154559-be6f3880-776e-11eb-9c24-6e80b4e58332.png)
And yes the user management is possible within Node-Red or can be routed to Auth0, Firebase, ...
Node-Red goes far beyond managing IoT, it's a very useful layer above NodeJS. And will be there to stay, since it's funded by IBM.

But it's poor on UI, only 2 options exists: Dashboard (Angular and not for full fledge web services) and UIBuilder (Vue).
In my previous example, customizing the login screen is through pasting html, css and js for validation.

On the other side, QuantUX is very very good on UI and prototyping a small REST, but when you'd want to implement OpenAPI structure (say the petstore example), you can generate all the routes in Node-Red from the OpenAPI declaration:
![image](https://user-images.githubusercontent.com/65325/109155705-2e31f300-7770-11eb-9bf5-8759e787c6d9.png)
These are not the route to an external service, but you just scaffold all your server routes!
Now it's yours to play with :sweat_smile: 

So, to me QuantUX+Node-Red could be the best of front-end and back-end for a visual artist like me :)
Hope it makes sense

**Comment by KlausSchaefers** [comment]
OK,

1) I would guess that Node.red exposes these endpoints. So you could have on server running the UI and one Node-Red. Wouldn't that work? Take a look at:

https://youtu.be/9Ex8do5vWaY

If you have the Node.red running at localhost:xxx you could use the web service blocks and link to this server. If this gets to cumbersome, you could use vue-low-code and code all the rest calls. Take a look here:

https://github.com/KlausSchaefers/vue-low-code-example

I simply load a Quant-UX design and link data and methods.

2) Regarding the responsiveness. Let me think a little about it and what I could do. If you go for vue-low-code you code just code some stuff around, e.g.

    <QUX v-if="isLandscape" app="...." v-model="viewModel" />
    <QUX v-if="!isLandscape" app="...." v-model="viewModel" />

This is maybe not the most efficient form, but it would do the trick. isLandscape could be a computed property.

**Comment by KlausSchaefers** [comment]
Would the Node-Red server expose an OpenAPI endpoint? I am asking because I was always thinking g about having a better support for swagger...

**Comment by j2l** [comment]
Hello Klaus, 
Sorry, I wasn't available the last 2 days.
Node-Red has 2 OpenAPI modules I can see from the palette:
![image](https://user-images.githubusercontent.com/65325/109392423-421a5800-791c-11eb-96be-8907dd06767d.png)
May be more if you install from node-red-contrib-... packages or from NPM, I use flowgen.
You also have more announces at https://discourse.nodered.org/search?q=openapi
I'm not affiliated with Node-Red

To reply to your previous points:
1- Yes, NR can serve as your REST backend, GET: http://localhost:1880/v2/store/inventory (or https://mydomain.com/v2/store/inventory).
It could serve you JSON, GraphQL, ... whatever
It can also serve your client, no need for another server. That's what I want to achieve because, beyond REST, you can setup functions directly related to your pages (see auth above).

2- "code some stuff around" e.g ...? Sorry, I don't see anything after e.g

AFAIU, there are 2 use-cases:
Simple REST client: can be 2 entities (NR + QuantUX widgets to Vue-low-code example).
Auth, more complicated stuff like e-commerce: best would be served by NR with Vue or even HTML+CSS, I think.

Can we auth a REST API (send/receive bearer JWT, register new user, read status, ...) using QuantUX?
When it's in business logic, I'd prefer NR.
Can we see https://quant-ux.com/#/apps/a2aa10arB99qzMjWYeimjhwnZ9Ece6VuRzt7B1jDRBKvfT6ija1AFgKgoYCK.html somewhere??
Do you have a tutorial to go from QuantUX to the vue-low-code-example?
I've seen your todo example video and found it hard on the business logic side.
Maybe because I'm a visual artist, not a real coder :)

**Comment by KlausSchaefers** [comment]
Hi,

you can use the REST nodes in quant-ux to query your endpoints. You can also save the response in some variables, that you can use later, e.g. auth tokens. Some times, configuring these REST nodes can be cumber some, for this case I suggest the vue-low-code solution. In there you would do the following:

1) Set up vue-low code project e.g. clone the todo example (https://github.com/KlausSchaefers/vue-low-code-example)

2) Change the share key in src/home.vue (https://github.com/KlausSchaefers/vue-low-code-example/blob/master/src/views/Home.vue)

3) If you start the server you should see the prototype

4) Now you can define callbacks in Quant-UX. Select an element (screen or widget). Change to the "Data & Code View". Enter there a method name for click or load events.

5) Reload the web page . if you click on the element, you should see an error in the developer tools, that a method is missing. 

6) Implement the method in home. The main parameter is an event, which carries all data

If this is not clear, I would suggest I do a short video call. You can reach me under Klaus.schaefers@quant-ux.com

**Comment by KlausSchaefers** [comment]
Take a look at this walk through... https://youtu.be/3hvWD7_opSY

**Comment by j2l** [comment]
Thank you very much for your new extensive video tutorial! I really appreciate :)
I just finished a 300h work and need some rest, I'll have a look ASAP

**Comment by j2l** [comment]
OK, I'm trying to wrap my mind around QUX and Node-Red+UIB+Vue (NRUIBV for short)

"Vue.use" helped me point to https://github.com/TotallyInformation/node-red-contrib-uibuilder/issues/83

but I get the error in Firefox:
`Uncaught ReferenceError: exports is not defined
    <anonymous> http://192.168.1.236:1880/uibuilder/vendor/vue-low-code/dist/index.js:8
index.js:8:1`

While Vue3 works fine on NRUIBV (not stated into NRUIB though). 
As tests, I simply copy paste exemples from https://v3.vuejs.org/guide/introduction.html#declarative-rendering and adds the library `<script src="https://unpkg.com/vue@next"></script>` to make them work.

Is qux-lowcode for Vue2 or Vue3? Or does it matter? :smile:

**Comment by j2l** [comment]
BTW, I try your (sometimes too fast :) ) example and while I get:
![image](https://user-images.githubusercontent.com/65325/109984420-0b6d8480-7d04-11eb-8e50-90c677282345.png)
![image](https://user-images.githubusercontent.com/65325/109984467-188a7380-7d04-11eb-90a8-cc1c4dc5bc3d.png)

my local result is different:
![image](https://user-images.githubusercontent.com/65325/109984537-29d38000-7d04-11eb-9551-d55e5ff970fb.png)

I missed something

**Comment by KlausSchaefers** [comment]
Hi,

can you add me as a team member (Klaus.schaefers@quant-ux.com) and I have a look. Seem to be a bug...

**Comment by j2l** [comment]
Thank you!
Done

**Comment by KlausSchaefers** [comment]
Some of the elements had "forbidden" characters, age "Pass (Show & Hide)". I think the low code doe snot like that. I fixed it for you by renaming the elements. Now everything should work fine. In the mean time I will fix that bug

**Comment by KlausSchaefers** [comment]
if you update due-low-code to 1.0.2 the issue should be gone too.

**Comment by j2l** [comment]
Thank  you, I didn't change anything to the password field.
About Vue3, does vue-low-code (vlc) could work with https://unpkg.com/vue@next?

**Comment by KlausSchaefers** [comment]
I changed the name... Currently it only works with Vue 2...

**Comment by j2l** [comment]
Today "export code" is broken for me (Firefox and Chromium on Linux). can't get Vue code anymore, only CSS.

**Comment by KlausSchaefers** [comment]
This seems like an old bug.. I will have to check that. For me this still works... For your setup you do not need this. The home.vue stay pretty much the same. The only thing that changes is the viewModel part. I hope you can add that in worst case by hand.

**Comment by TotallyInformation** [comment]
Wow, some interesting stuff here. Sounds like Node-RED, uibuilder and quant-ux is a marriage made in heaven.

Let me know if there is anything I can do to help on the uibuilder side.

I'm certainly very keen to see this setup in action and would love to get a write-up into the uibuilder WIKI so that other people can have a low-code way of building data-driven Vue web apps.

**Comment by j2l** [comment]
Great to see you 2 are finally finding each other :smile: 
Hope [it](https://discourse.nodered.org/t/uibuilder-vue3-rest-better-than-my-hack/42096/3) helped
