### ISSUE TITLE
It is not possible to adjust the cursor position when editing a "Text component"

### ISSUE THREAD

**Issue by jrodrigosousa** [KlausSchaefers/quant-ux#321]
# Describe the bug

When it is necessary to adjust the content of a text component (primary text or secondary text) sometimes the user wants to move the cursor to the beginning of the text or some intermediate position to make the edit, but often it is not possible to do this.

### To Reproduce

It's an intermittent problem and I don't know how to reproduce it all the time. But it happens when there is a text component already filled with some content and the user clicks on the text in order to edit it. The interface releases the editing mode, but does not allow the cursor to be repositioned to any place other than the end of the text.

### Expected behavior

Whenever the user needs to edit the text, it should be possible to position the cursor anywhere in the text and change it normally with the mouse or the keyboard arrows, as in any text editor.

### Browser

- [x] Chrome
- [x] Edge
- [ ] Firefox
- [ ] Safari

### Operating System

- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by KlausSchaefers** [comment]
Hi,

thanks for pointing this out. The issue happens if the element is embedded in a bigger element. If it is for example the only element on the screen, the selection should work. This is related to the retarded why I handle drag and drop :( I will try to fix this.

Thanks,

Klaus

**Comment by KlausSchaefers** [comment]
Should be fixed
