### ISSUE TITLE
All prototype components suddenly disappeared

### ISSUE THREAD

**Issue by cjayneb** [KlausSchaefers/quant-ux#325]
# Describe the bug

I created a prototype last week called SuperNotes. This prototype worked fine and I was able to add screens and anything I wanted. I shared the prototype with my classmates so that they would be able to edit it.

It was working for everyone. Everyone was able to add or remove stuff.

Now for some reason, since last friday, no one is able to see anything when opening the prototype. Just a grey and black background. No screens, buttons, etc,.. You could easily say someone just deleted everything but **No one is able to add anything to it either.** 

It is impossible to test it either. When pressing the play button, only a grayish overlay appears.

### To Reproduce

Not sure exactly how to reproduce this because this is the first time it happens and it happened seemingly out of nowhere.

1. Create prototype
2. Share it with people
3. Have other people edit the prototype
4. Come back to the prototype half a week later and see what is portrayed in the Screenshots section

### Expected behavior

- I expect that the prototype components will all be present and intact when I open the prototype.
- I expect to be able to add more components and continue editing.
- I expect to able to test my prototype by pressing the play button.

# Screenshots

![image](https://github.com/user-attachments/assets/0a50da30-58a0-4efc-86c6-f0b090afd56c)
![image](https://github.com/user-attachments/assets/6aa521a7-b3f7-45c3-879f-fc7d9de9fe39)
![image](https://github.com/user-attachments/assets/097f59bf-786d-4e39-b89b-df4bda027f3f)

When pressing play to test it
![image](https://github.com/user-attachments/assets/8c02e226-3ef4-4c80-a40f-9864cc13ee69)

# Context

_Select all the browsers and OSs where the issue is observed_

### Browser

- [X] Chrome
- [X] Edge
- [X] Firefox
- [ ] Safari

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Extra

Additional Context: 6733e8856ee8381b3ce91e2d seems to be the id of the problematic prototype, if that can help debug 🫤 
Temporary workarounds, if any:

**Comment by cjayneb** [comment]
@KlausSchaefers I have added your email to the team (I assumed you meant [klaus.schaefers@quant-ux.com](mailto:klaus.schaefers@quant-ux.com)).

Let me know if you need anything else :)

**Comment by KlausSchaefers** [comment]
Hi,

It seems somehow the app data was corrupted. I removed the messed up data. I think it should not have any impact on the design. Could you please check?

**Comment by cjayneb** [comment]
@KlausSchaefers Yes everything seems to be working fine. Thank you so much for the fast support.

Hope you have a great day!
