### ISSUE TITLE
How to get a date and time to a field?

### ISSUE THREAD

**Issue by j2l** [KlausSchaefers/quant-ux#33]
I'd need to select a date and an time and get a field filed out
![image](https://user-images.githubusercontent.com/65325/108917108-87ded400-762f-11eb-86d9-65f7587d7d82.png)
I didn't get how to do that :)

**Comment by KlausSchaefers** [comment]
There are date picker widgets, but not a date time picker. I will add this to my backlog.

**Comment by j2l** [comment]
Thank you again!
Once implemented, please let me know how to fill a field with time and date (UTC format or else).

**Comment by j2l** [comment]
Closing it for now :)
