### ISSUE TITLE
NetworkError on REST test. CORS issue

### ISSUE THREAD

**Issue by j2l** [KlausSchaefers/quant-ux#34]
Following your great tutorials, I try to call a mockup REST API (https://6041e60f7f50e000173ab43e.mockapi.io/api/v1/animals) to fulfill the test https://www.youtube.com/watch?v=9Ex8do5vWaY
However, I get:
![image](https://user-images.githubusercontent.com/65325/110086464-af9e0c80-7d92-11eb-9f36-f991573688fd.png)

Console:
 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://6041e60f7f50e000173ab43e.mockapi.io/api/v1/animals. (Reason: header ‘authorization’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

14:54:54.802 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://6041e60f7f50e000173ab43e.mockapi.io/api/v1/animals. (Reason: CORS request did not succeed).

**Comment by KlausSchaefers** [comment]
Hi,

there was a bug and I fixed it. Can you reload and try out. In vow-low-code the fix will come later

**Comment by j2l** [comment]
Yes, CTRL+F5 and it works now :)

**Comment by j2l** [comment]
To be closed as soon as fixed in Vue Low Code :)

**Comment by KlausSchaefers** [comment]
Fixed

**Comment by j2l** [comment]
Great, thanks!
