### ISSUE TITLE
can't POST

### ISSUE THREAD

**Issue by j2l** [KlausSchaefers/quant-ux#35]
Hello!
OK, as you might know, I'm a student (cinema and new media) and I'd like to collect reviews from my class about my design in QuantUX (might be future customers for you too! :smile: ).

To do that, I think of buttons on a master page (like, dislike, average, ...) that POST (using your REST service) to my home server (NR).
but I'm getting error:
![image](https://user-images.githubusercontent.com/65325/110445799-c7410200-80be-11eb-9623-e80f426bf867.png)
Of course domain name and path are valid, not mydomain.com and posturl.

I'm sure my service works, I tested it with postman.

**Comment by j2l** [comment]
You're right :) Fixed!
Just before closing the ticket, how to to post the screen name?
My "form" is in the master screen and I'd need to add the screen name:
![image](https://user-images.githubusercontent.com/65325/110450995-09b90d80-80c4-11eb-8d88-4e2721464f92.png)
I have 2 services, one for each, but if there's a way to change reply based on a condition, I'd love to know.

**Comment by j2l** [comment]
Do you develop only on Chrome? 
On Firefox, there are weird selection glitches:
- duplicating a screen selects a random rectangle elsewhere
- clicking on simulate, selects some text (you can't deselect):
![image](https://user-images.githubusercontent.com/65325/110478594-cae77f80-80e4-11eb-8a2f-963249548206.png)
and more

**Comment by KlausSchaefers** [comment]
Hi,

I only test on Chrome and Safari. If I am pointed at a issue in FF I will off course fix it. I am currently working on Version 4. I will try to include the FF fixes there, but it will still take some weeks or month until 4.0 is ready...

**Comment by j2l** [comment]
> Hi,
> 
> I only test on Chrome and Safari. If I am pointed at a issue in FF I will off course fix it. I am currently working on Version 4. I will try to include the FF fixes there, but it will still take some weeks or month until 4.0 is ready...

Ok, I switch to Chrome for now.

**Comment by j2l** [comment]
> The easiest would be to have different REST symbols and pass the screen name somehow as part of the request, e.g. as a field in the post. Currently there is no quick way to assign a value to a variable...( I will add that to my backlog)

If there's a screen identifier in the URL I can extract? in addition to the prototype uuid

**Comment by j2l** [comment]
> The easiest would be for me to introduce some magic variables, like '$qux.screen'. Would that help you?

Yes, definitely! I already have 65 clicks (good and bad opinions) and can't tell which screen it relates to :)

**Comment by KlausSchaefers** [comment]
OK, please reload the browser. There is now a magic screen variable called '**_qux.screen
![MagicScreen](https://user-images.githubusercontent.com/7108416/110550632-f9d51400-812b-11eb-86ac-d247ad8f2460.png)
**'. I can not promise that it will stay forever, maybe at some point in the future I will build a better solution.

**Comment by j2l** [comment]
Great!
However, when I add it to the url using `nnnnn.com/avis?ecran=${_qux.screen}`, it coughs:
![image](https://user-images.githubusercontent.com/65325/110593483-e94c8a00-817b-11eb-8eb2-67bc8ca36ed9.png)
Same when, instead, I add it in the body:
![image](https://user-images.githubusercontent.com/65325/110593668-29137180-817c-11eb-930c-4d998c8f12d6.png)
Or should I GET the screen first and pass it to POST?
But how to add it in the post?
Thank you!

**Comment by KlausSchaefers** [comment]
You have to provide inout when clicking on test. In the simulator the value is set automatically. 
Can you try in the Simulator?

**Comment by KlausSchaefers** [comment]
when you post, do not forget to include " marks

```
{
  "a": "${_qux.screen}"
}
```

**Comment by j2l** [comment]
Yes, I added it right after my post, still the same.
Ok, I cleared the console, went to config, added your "a" in JSON and got this:
![image](https://user-images.githubusercontent.com/65325/110600866-b2c73d00-8184-11eb-83e4-891ecadbf963.png)

Oooh, only the test is whining, the REST service is working fine though, OK.
So I can close it :)

**Comment by KlausSchaefers** [comment]
Hm, for me this works also with the test. But good that it works in the simulator.
