### ISSUE TITLE
Can't delete a comment

### ISSUE THREAD

**Issue by othomation** [KlausSchaefers/quant-ux#36]
Hello,

When I try to delete a comment in my prototype (editing mode), it does nothing.

In the console of the dev tools i have this error :

```javascript
AbstractService.js:202 Uncaught (in promise) Error: Could not delete
    at AbstractService.js:202
(anonymous) @ AbstractService.js:202
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
onDeleteComment @ Comment.vue:416
(anonymous) @ lang.js:24
```

So here is the piece of code from `AbstractService.js`
```javascript
 _delete(url, successCallback, errorCallback, header) {
        return new Promise((resolve, reject) => {
            fetch(url, {
                method: 'delete',
                headers: this._createDefaultHeader(header)
            }).then((res) => {
                if (res.status === 200) {
                    res.json().then(j => {
                        this.logger.log(6, '_put', 'exit ')
                        if (successCallback) {
                            successCallback(j)
                        }
                        resolve(j)
                    })
                } else {
                    this.onError(url, res)
                    if (errorCallback) {
                        errorCallback(new Error('Could not delete ...'))
                    }
                    reject(new Error('Could not delete'))
                }
            }).catch(function (err) {
                if (errorCallback) {
                    errorCallback(err)
                }
                reject(new Error('Could not delete'))
            })
        })
    }
```

I'm using QUANT-UX on https://quant-ux.com/

Thanks;

**Comment by KlausSchaefers** [comment]
Hi,

this seems to be the case for comments that were not originated by the current user., e.g. a guest.

**Comment by KlausSchaefers** [comment]
Can you create and remove a comment, just to confirm my analysis?

**Comment by othomation** [comment]
Hello,

So I can delete my own comments, but not other from Guest or from collaborators.


Also, i tried to add a comment as myself (creator of the prototype), and it say it's from a Guest.
I'm unable to even see it !

 I disabled/enabled (the checkbox) comments (top right menu), then I can open it and it is now under my name and not Guest as at the creation.

**Comment by KlausSchaefers** [comment]
Hi, can you try out now? I changed the permission model a little, and now the editors can remove all comments. I could not recreate the issue, that new comments are created as guest. I will still have to look into that.

**Comment by othomation** [comment]
Hello,

I just tried, I can now remove comments of other, work like a charm !
