### ISSUE TITLE
I want to avoid proxy and set the url directly

### ISSUE THREAD

**Issue by SharifTanvir** [KlausSchaefers/quant-ux#38]
I have already updated your services folder's all js files by adding my API URL like 

` signup (data) {
        return this._post('https://api.prototype.tikweb.com:8080/rest/user', data)
    }`

But I am not getting the project creating option after login. I am getting the error "Uncaught (in promise) TypeError: Failed to fetch"

**Comment by KlausSchaefers** [comment]
So you changed the ModelService to include the direct URL? I have nether tried this. I enable CORS, in the backend:

```
	/**
		 * Set body and cookie handler
		 */
		Router router = Router.router(vertx);
		router.route().handler(BodyHandler.create().setMergeFormAttributes(false));
		router.route().handler(CorsHandler.create("*")
				.allowedMethod(HttpMethod.GET)
				.allowedHeader("Access-Control-Request-Method")
				.allowedHeader("Access-Control-Allow-Credentials")
				.allowedHeader("Access-Control-Allow-Origin")
				.allowedHeader("Access-Control-Allow-Headers")
				.allowedHeader("Content-Type"));

```

But maybe there is something wrong. If you run the request with CURL or Postman they work?

**Comment by KlausSchaefers** [comment]
Also, I cannot reach https://api.prototype.tikweb.com:8080/rest/status.com

**Comment by SharifTanvir** [comment]
I have changed ModelService but getting the error "Uncaught (in promise) TypeError: Failed to fetch" after login.

Use `https://api.prototype.tikweb.com:8080/rest/status.json`

**Comment by KlausSchaefers** [comment]
I still cannot reach the server. I made a prototype te test if it is an CORs issue:

https://quant-ux.com/#/test.html?h=a2aa10aetVqsP3akLkz4ywFYBaIAuc5ExJdHjQpvoar4oL9RVy8CuHladcry&log=false

The 'test Direct' button is wired to your server, the proxy one to the live server through the proxy.

**Comment by SharifTanvir** [comment]
I am getting ok with both buttons.
and these value
Test Proxy => ok 3.2.1
Test Direct=> ok 3.0.4

**Comment by KlausSchaefers** [comment]
SO, this looks like there is no CORS issue. Can you send me the developer tools errors? If you right click in the dev tools you can copy the request as curl. Can you send that to me?

**Comment by KlausSchaefers** [comment]
Hi, how is your current status?

**Comment by SharifTanvir** [comment]
Sorry, i missed your last comment.
I have solved the issue. I am very thankful to you for your support.
