### ISSUE TITLE
Cannot delete an item copied from one screen to another.

### ISSUE THREAD

**Issue by floricelhernandez** [KlausSchaefers/quant-ux#39]
I have placed a label inside a first screen, in the same way I created a table inside it, the elements have not been copied inside the second screen but outside of it. I have tried to delete them but it is not possible. It indicates that it is associated with my master file, even enabling editing it cannot be deleted. 
Using 
![Captura de pantalla de 2021-03-28 10-28-53](https://user-images.githubusercontent.com/6853786/112759495-741ce980-8fb0-11eb-9d7a-3c9dfc7dfd11.png)

Google Chrome in Linux

**Comment by KlausSchaefers** [comment]
Hi,

this looks like a bug. Can you share the prototype with me? Klaus.schaefers@quant-ux.com. In rare cases the relation between screens and element has been messed up. This just fix item could you try:

1) Reload the page

2) Move the master screen around

3) Can you delete the element from the master screen?
