### ISSUE TITLE
Bugs, bugs, bugs all around

### ISSUE THREAD

**Issue by FahadZaheerfzr** [KlausSchaefers/quant-ux#40]
Copying an item gives a bug.
Replicating the screen gives a bug.
Replicating components also gives bugs.

**Comment by KlausSchaefers** [comment]
Hi,

thanks for you feedback. I cannot reproduce your issues on the reference system. Which browser are you using? Which OS? Do you have any add blocker installed? 

What do you mean with replicating? A more precise description would help to fix those issues.

Cheers,

Klaus
