### ISSUE TITLE
Desktop app?

### ISSUE THREAD

**Issue by iwoithe** [KlausSchaefers/quant-ux#41]
Hi there,

I saw [this](https://github.com/KlausSchaefers/quant-ux-electron) repository and so I am wondering if there will be a desktop app or not.

Thanks

**Comment by KlausSchaefers** [comment]
Hi,

I have started but never had to time to finish :(

**Comment by iwoithe** [comment]
Is it possible to give a timeline?

**Comment by KlausSchaefers** [comment]
Hi,

How would you envision the app to work?

1) Should the app run completely offline and store the design in the file system? In such a case the testing would not work.

2) Or should the app just replace the browser, but all data is stored in the cloud.ö In this case testing would work?

The second option is much easier, however would not provide true offline capabilities. 

Currently the desktop app is really low on my priority list. If you like, I can assist you with the implementation. 

Kind Regards,

Klaus

**Comment by iwoithe** [comment]
> Should the app run completely offline and store the design in the file system?

In my opinion, yes. I work offline a lot, and so cloud based storage would not work well.

> I can assist you with the implementation

I would love to help out, but unfortunately I've got close to no experience with Node.js apps (although I'm happy to learn if needed).
