### ISSUE TITLE
User of team avatar is not good recognizable

### ISSUE THREAD

**Issue by Samuel-Schober-USU** [KlausSchaefers/quant-ux#44]
![image](https://user-images.githubusercontent.com/74423194/125084753-2b55f000-e0ca-11eb-82b5-5e33d80ee837.png)

It would be cool if we would be able to see the team member name when hovering the avatar. Alternatively you could display first letter of firstname and lastname instead of only firstname, to reduce the risk of not unique avatars.

**Comment by KlausSchaefers** [comment]
Hi,

The avatar name is derived from the profile. If users enter a name and last
name, the avatar will have two characters, I will check if there is a bug.
If one uploads a profile picture, this will be shown instead.

The tooltips are a great idea. I will implement this soon.


Samuel-Schober-USU ***@***.***> schrieb am Fr., 9. Juli 2021,
14:30:

**Comment by KlausSchaefers** [comment]
I think I improved. Would you be so kind to check?

![Team](https://user-images.githubusercontent.com/7108416/125175648-7143ae80-e1c5-11eb-8732-a36f34c6ce9f.png)

**Comment by Samuel-Schober-USU** [comment]
![image](https://user-images.githubusercontent.com/74423194/125250609-bf0c0400-e2f6-11eb-892d-ddaa47ea7077.png)

Works great and an amazing responsetime, thanks :)
