### ISSUE TITLE
Comparing two databinding variables

### ISSUE THREAD

**Issue by LechoDecho** [KlausSchaefers/quant-ux#45]
Hello, 

is there a way to compare two databinding variables with each other when using the logic operator. 
As far as i can see there is only the possibility to compare a variable with a "hardcoded" value.

Thanks and great work so far!

**Comment by KlausSchaefers** [comment]
That is a nice idea. I will implement it in the next weeks.

**Comment by KlausSchaefers** [comment]
Hi,

I added a simply solution. If you now type in the value box a 'data bringing variable path', the value will be compared against the associated value. To do so, one has to use the `${variable}` notation.
![Qux-New-DataBinding](https://user-images.githubusercontent.com/7108416/126218762-78b966b7-5fbc-45ab-a810-92d6b26b03eb.png)

**Comment by LechoDecho** [comment]
Thanks for the quick solution! I will test it in the future!
