### ISSUE TITLE
Exporting Quant-UX Prototype

### ISSUE THREAD

**Issue by LechoDecho** [KlausSchaefers/quant-ux#47]
I'd like to export my current prototype to include it in my own git repository. 
With so i can have some sort of versioning on my quant-ux prototype and can return to or view a certain previous version if needed to.

Thanks for your work!

**Comment by KlausSchaefers** [comment]
I will look into this. Git support is a nice feature!

**Comment by KlausSchaefers** [comment]
Hi, there is now a ZIP export. Would that be good enough for you?
