### ISSUE TITLE
Initial databinging

### ISSUE THREAD

**Issue by LechoDecho** [KlausSchaefers/quant-ux#48]
Widgets on a screen do not have initial values in their databinds. The user always needs to interact at least once with an widget to have a value bind. This makes some interactions for the testing user not intuitive and unnatural.

Thanks for your work!

**Comment by KlausSchaefers** [comment]
Thanks for raising this point. I will think about a better solution for this!

**Comment by KlausSchaefers** [comment]
You can now use the Script component with the "Loaded Trigger":

https://quant-ux.com/#/help/scripts/script.auto1.html
