### ISSUE TITLE
About APK

### ISSUE THREAD

**Issue by xiao199336** [KlausSchaefers/quant-ux#49]
Hi!

This is the best open source prototyping tool I have ever seen, but at the moment I have encountered a huge problem.

When I use a tool to generate a prototype product, how do I get the static resources of this prototype product, because I want to generate an apk project through static resources, or do you have any other suggestions to generate an apk file?

Thank you for your job, and answer!

**Comment by KlausSchaefers** [comment]
Hi,

you can take a look at https://github.com/KlausSchaefers/vue-low-code and https://github.com/KlausSchaefers/quant-ux-cli. Both projects allow some form of low code and code generation. You can modify the code bases to generate android artifacts if you want.

Kind Regards,

Klaus
