### ISSUE TITLE
I am getting 500 (Internal Server Error) while uploading an image

### ISSUE THREAD

**Issue by SharifTanvir** [KlausSchaefers/quant-ux#51]
I can login and signup and also can view my existing works. But when I try to upload an image it shows me the error. 

N.B: I have my own setup for both front-end and back-end. 
https://prototype.tikweb.com/#/

**Comment by KlausSchaefers** [comment]
Hi,

are you using a reverse proxy or so? Sometimes the might limit the request size and block large requests.

Cheers,

Klaus

**Comment by KlausSchaefers** [comment]
Also, the image uploads expects the doe.js proxy to be active. All request go to "'/rest/images/", this means the front-end server. From there request need to be forwarded to the java backend. I think we discussed this proxy issue once, or am I mistaken?

Cheers,

Klaus

**Comment by SharifTanvir** [comment]
Yes. We talked about proxy before. And the settings were smooth. We just faced this problem from a few days.

**Comment by KlausSchaefers** [comment]
Hi,

in this case, the image request will go to the front end server, where the UI expects a proxy. You would need to update the upload URL.  Take a look at the ImageService class. There you would have to rewrite the URL.
