### ISSUE TITLE
Is there a plan to support vue3？

### ISSUE THREAD

**Issue by konglinghai123** [KlausSchaefers/quant-ux#52]
Look forward to your reply ！

**Comment by zbLiuLiu** [comment]
@KlausSchaefers Is there a plan to support vue3 now?

**Comment by KlausSchaefers** [comment]
Why?

“Overfitting” is not about an excessive amount of physical exercise...

LiuLiu ***@***.***> schrieb am Sa., 1. Nov. 2025, 13:27:

**Comment by KlausSchaefers** [comment]
Porting to vue3 will be a mayor undertaking, which will likely need months
of work until the platform is stable and will not have any immediate
benefit.

As my time is limited, I prefer to focus on more tangible tasks. If you are
interested I porting, I can share some points which will need special
attention.

Look forward,

Klaus



“Overfitting” is not about an excessive amount of physical exercise...

Klaus Schaefers ***@***.***> schrieb am Sa., 1. Nov. 2025,
23:08:
