### ISSUE TITLE
Is there a plan to get ride of dojo

### ISSUE THREAD

**Issue by chenshuichao** [KlausSchaefers/quant-ux#54]
You know dojo is so old and dojo is not dev.

**Comment by KlausSchaefers** [comment]
Hi,

we have long ago moved from Dojo to Vue. However, there were a lot of dependencies to Dojo, so we reimplemented the needed function in Vue. This is what you can find in the src/dojo package. So, there are some functions with the same signatures, but they not from Dojo.

Does this answer your question?

Cheers,

Klaus

**Comment by chenshuichao** [comment]
Thank you!
