### ISSUE TITLE
arco design

### ISSUE THREAD

**Issue by chenshuichao** [KlausSchaefers/quant-ux#55]
https://arco.design/
How can I import arco design system?

**Comment by KlausSchaefers** [comment]
Hi,

you need to rebuild the elements in Quant-UX. There is no support for external components.

Cheers,

Klaus

**Comment by KlausSchaefers** [comment]
You do not need things like Arco, Quant-UX supports the Luisa framework: https://luisa.cloud

**Comment by chenshuichao** [comment]
Great!
Maybe we just need more some documents and examples.
For example, If we can guide the process about transferring from figma to code.

**Comment by chenshuichao** [comment]
@KlausSchaefers thank you!

**Comment by KlausSchaefers** [comment]
Hi,

can you have a look at https://luisa.cloud/help.html? This is still in beta. I have tried to outline how you can turn Figma to an VUE app.
