### ISSUE TITLE
[Enhancement] Cannot add other headers in Rest service settings rather than auth token

### ISSUE THREAD

**Issue by zcpp** [KlausSchaefers/quant-ux#57]
Hi @KlausSchaefers , Is there any plan to add customizable header setting for Rest service?

Currently it only supports to set auth token. That would be very helpful if it supports to add other customized headers - and supports to set header key or value from a model variable. e.g.: 
![1638265386(1)](https://user-images.githubusercontent.com/5620097/144023654-b4a0a6f0-465d-446e-a82b-a172cd938802.png)

Also it would be great to support so in Luisa vue library.

**Comment by KlausSchaefers** [comment]
Great idea. I will try to fix this soon.

**Comment by KlausSchaefers** [comment]
Hi,

can you try out? The improved REST component is online.

![QUX_REST_Headers](https://user-images.githubusercontent.com/7108416/144912571-dc0547dc-918d-4fed-bcf3-6aa752f1f881.png)

**Comment by zcpp** [comment]
@KlausSchaefers  Hi, thanks for your work.  Cool improvement!   I've also tried the latest luisa library - now the new RestEngine can load headers from exported json and make REST request with them.
