### ISSUE TITLE
AGPL instead of GPL?

### ISSUE THREAD

**Issue by 12people** [KlausSchaefers/quant-ux#6]
Given that Quant UX is a web application, the Affero GPL v3, which is the same as the GPL v3 except it extends the copyleft to software published over the network, would seem more fitting for the project.

**Comment by KlausSchaefers** [comment]
Hi,
as far as I understand software licensing, Quant-UX  is distributed, when a user opens the web page. All the JS code is downloaded to the client. For me, GPL3 seems fitting to this case.

**Comment by 12people** [comment]
The AGPL would require code to be shared even when the JS code is made to be run server-side.
(And that is its sole and only difference from the GPL.)

**Comment by KlausSchaefers** [comment]
I believe this code cannot really be run server side.... At least for me this would not make much sense.

**Comment by 12people** [comment]
Alright, sure, makes sense.
The AGPL would be more relevant for the server-side code, once that's released.
