### ISSUE TITLE
How do I add element's logic to the screen? 

### ISSUE THREAD

**Issue by konglinghai123** [KlausSchaefers/quant-ux#62]
I want to do some easily logic. for example, I have a ComboBox that can I  hide another element on the current screen.

**Comment by konglinghai123** [comment]
Could you please add a features which can define element action or link screen by javascript. such as 'OR' component.

**Comment by konglinghai123** [comment]
I want to do some easily logic. for example, I have a ComboBox that can I hide another element on the current screen.

**Comment by konglinghai123** [comment]
I want to do some easily logic. for example, I have a ComboBox that can I hide another element on the current screen.

Could you please add a features which can define element action or link screen by javascript? such as 'OR' component

**Comment by KlausSchaefers** [comment]
Hi,

I am not sure if I would solve toggle visibility with JS. The "element action" is another good alternative. There are however some limitation. If you toggle visibility, the page will not reflow, e.g. if you remove one section, the section below will not move to the top. 

In the next weeks I am quite busy, so this might take some time. Until then you could solve the issue by creating multiple versions of you screen and linking them to get the toggle effect.

Cheers,

Klaus

**Comment by konglinghai123** [comment]
The "element action" is very important features. Could you please tell me some tips to develop this feature?

**Comment by konglinghai123** [comment]
I don't expect to be able to preview in real time in the simulator. What I expect more is that the element action can be implemented when the vue-low-code project is running.

**Comment by KlausSchaefers** [comment]
Hi,

thanks for offering help!

**In Quant-UX:**
Take a look at the "ActionButton" https://github.com/KlausSchaefers/quant-ux/blob/master/src/canvas/toolbar/components/ActionButton.vue

**In vue-low-code**
There also the "back" action is set. I would add a new option, like "element action". The action will be saved in the "props" of the widget. This should be available in due-low-code.

In vue-low-code extend the "Event" https://github.com/KlausSchaefers/vue-low-code/blob/master/src/qux/mixins/Event.vue class. I think global state would be best. One could share over an "provide" from the Luisa.vue component to all the children, just like the viewModel:

https://github.com/KlausSchaefers/vue-low-code/blob/master/src/qux/Luisa.vue

So something like 

```JavaScript

 data: function () {
      return {
        ...
       viewState:{}
      }
  },
..
 provide() {
    return {
      viewModel: this.modelValue,
      viewState: this.viewState
    }
  },
 ...
 methods: {
   setWidgetState (id, visible) {
        if (!this.viewState[id]) {
          this.viewState[id] = {visible:true, ....}
        }
        this.viewState[id].visible = visible
  }
}
```

In the _Base https://github.com/KlausSchaefers/vue-low-code/blob/master/src/qux/web/_Base.vue  inject the viewState prop and extends the "cssClass" computed prop

```

  inject: ['viewModel', 'viewState'],

...
computed: {
   cssClass () {
        let result = 'qux-element '
        if (this.element) {

            ...
           if (this.viewState[this.element.id]) {
                let state = this.viewState[this.element.id]
                if (!state.visible) {
                    result += ' qux-hidden '
                }
           }
        }

        

        return result
      },
```

Does this help? If you have some initial code, I can review and comment.

**Comment by KlausSchaefers** [comment]
Side node, in the action button I would but complex configurations for the actions in a dialog, like the animation properties.

**Comment by konglinghai123** [comment]
Thanks Klaus ! I try to do it.
