### ISSUE TITLE
Question regarding code export

### ISSUE THREAD

**Issue by flotho** [KlausSchaefers/quant-ux#63]
Hi,

I would like to thank you for the great tool you're providing as an open-source solution. It's really powerful.
I also observed that you're providing a beta feature to generate vue.js code thanks to this project.
Is it possible to point me where this generation is done and could you share with us if your code structure will allow to generate code in other framework? (if we contribute for sure)

thanks in advance for your answer.

Best regards

**Comment by KlausSchaefers** [comment]
Hi,

in Quant-UX I generate only CSS. It happens in this package:

https://github.com/KlausSchaefers/quant-ux/tree/master/src/core/code

The standalone low-code framework is here:

https://luisa.cloud/

Kind Regards,

Klaus
