### ISSUE TITLE
Dockerized front and backend?

### ISSUE THREAD

**Issue by bmcgonag** [KlausSchaefers/quant-ux#65]
I would love to try this as a self hosted option, but feel it would need far less if it were dockerized for the front and back ends separately, and built into a docker-compose.yml file. 

Would you be willing to do that?

**Comment by KlausSchaefers** [comment]
Hi,

I will invest some time in the next weeks to make custom installations easier. I will also try to build docker images, although I am not really an expert on this... so I cannot promise any deadlines.

**Comment by bmcgonag** [comment]
I truly appreciate the effort. I can try to help, if I can get the build to work at all first.  I haven't tried yet.

**Comment by bmcgonag** [comment]
As an update, I'm attempting to build this into a docker app, but for now was trying to build it in one docker container.  I think I'm going to split it into 2, one front, one back.  On the Java 1.8, I'm using openjdk-11-jre, is there any reason that would give an error?

I get the following when running the java command in the Dockerfile build:

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Feb 18, 2022 1:34:39 PM io.vertx.core.Starter
SEVERE: Failed in deploying verticle
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at io.vertx.core.json.JsonObject.getInteger(JsonObject.java:149)
	at com.qux.MATC.initInvitationRest(MATC.java:380)
	at com.qux.MATC.start(MATC.java:123)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KlausSchaefers** [comment]
Hi,

this is an issue related to the config. You are using ENV or the JSON. I found a small bug and will commit the fix now. When it reads the port number from the ENV it does not convert it to int...

**Comment by bmcgonag** [comment]
I'm using the ENV, as this allows me to later let the user change those values as needed in their docker run, or docker-compose.yml.

**Comment by bmcgonag** [comment]
got this still with a fresh pull and new image build:

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Feb 18, 2022 2:38:47 PM io.vertx.core.Starter
SEVERE: Failed in deploying verticle
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')

```

**Comment by bmcgonag** [comment]
I had it without quotes, and then put quotes around it to try, but still get the same exception.  I'm digging in to see what may be wrong.

**Comment by bmcgonag** [comment]
I see one thing may be an issue. You modified the project yesterday, but the built version in the server folder still shows 3 months ago.  Did that get rebuilt with your changes?  I'm using that, and not building the project in the Dockerfile.

**Comment by KlausSchaefers** [comment]
Hi, thanks for noticing. I uploaded the latest release.

**Comment by bmcgonag** [comment]
Ok, that seems to have worked. I have the Backend done. Now let me get the front end, and try to make them work together in a docker-compose file.

**Comment by KlausSchaefers** [comment]
Hi,

there will be in the next days a smaller change to enable better configuration. Currently the web socket server is hardwired. I would like to make this configurable...

https://github.com/KlausSchaefers/quant-ux-websocket

I also need to make the web socket configurable...

**Comment by bmcgonag** [comment]
will that affect the start.js file?  I just realized it would be better to set the url via the env set in the Dockerfile, as this allows the end user to use the ENV to change it as well, and keeps them from having to modify the actual js file.

**Comment by bmcgonag** [comment]
Ok, made a modification to allow the user to enter the url for the proxy via an ENV, and when I start the app using `node server/start.js` it starts, and I can access it via the port 8082, but I can't get to it via the proxy, which I'm setting as localhost.

Code I'm using (1 addition, 1 change)
Addition:
`const target_server = process.env.SERVER_URL;` at top of start.js file.

Change:
```
app.use('/rest/', proxyMiddleware({
    target: target_server,
    changeOrigin: true
}))
```
Set the ENV in cli with:
`export SERVER_URL=http://localhost`

Result in terminal when running `node server/start.js`

```
quant-ux$ node server/start.js
[HPM] Proxy created: /  ->  http://localhost
 ______     __  __     ______     __   __     ______   __  __     __  __
/\  __ \   /\ \/\ \   /\  __ \   /\ "-.\ \   /\__  _\ /\ \/\ \   /\_\_\_\ 
\ \ \/\_\  \ \ \_\ \  \ \  __ \  \ \ \-.  \  \/_/\ \/ \ \ \_\ \  \/_/\_\/_
 \ \___\_\  \ \_____\  \ \_\ \_\  \ \_\\"\_\    \ \_\  \ \_____\   /\_\/\_\ 
  \/___/_/   \/_____/   \/_/\/_/   \/_/ \/_/     \/_/   \/_____/   \/_/\/_/ 
Listening on 0.0.0.0:8082

```
I presume the http://localhost should redirect to 0.0.0.0:8082 (or in this case http://localhost:8082

**Comment by bmcgonag** [comment]
Ok, i'm getting the front end and back end to run in Docker, but I need to understand the proxying you're doing.

The QUX_PROXY_URL / is that intended to be the URL of the applicatioin (the url I would put in the browser to login and so on)? or is it the QUX_HTTP_HOST environment variable set for the backend?

Finally, how does the front end know how to talk tot he backend?

If I can understand this more clearly, I think we'll have a working docker setup.
Thanks again for the fixes and help on this.

**Comment by KlausSchaefers** [comment]
Hi,

The front end always talks to '/rest/...' The proxy needs to forward all these request to the backend. So the name QUX_PROXY_URL is maybe not fully clear, it is basically the host + port of the backend, e.g. "https://api.server.com:808"

In the backend, the QUX_HTTP_HOST is the url of the front end. This is injected for instance in the emails. So, if you have the backend at **server_backend:8080** and the frontend at **server_frontend**, the correct settings would be

QUX_HTTP_HOST = https://server_frontend
QUX_PROXY_URL = https://server_backend:8080

I could change the keys to QUX_FRONT_END_HOST and QUX_BACKEND_HOST of you think it makes more sense.

**Comment by bmcgonag** [comment]
No, I think that's good, just needed to understand how the application was working, I think I can work this out to get the pieces talking.

**Comment by KlausSchaefers** [comment]
Hi,

you might also want to install the web socket server, to have collaborative editing in the canvas. Take a look here:

https://github.com/KlausSchaefers/quant-ux-websocket

The UI needs to know the URL of the web socket server, you can pass it since two hours also as a ENV parameter:

```
export QUX_WS_URL= wss.quant-ux.server.com
```

In the server/start.js there is not a small hook, which exposes the ENV variable to the browser.

**Comment by bmcgonag** [comment]
Ok, I see the project, but how do I run the websocket project? I assume it's not pulled down with the quant-ux front end project.

**Comment by bmcgonag** [comment]
Ok, I have the project (minus the websocket support) up and running using a backend docker image, a front end docker image, and a mongo image.  

I can load the page, and sign up successfully. When I try to create a project, however, I give it a name, and then select a device size, and click 'Create' - I get the following in the terminal:

```
quant-ux-backend | 09:13:44.248 [vert.x-eventloop-thread-0] ERROR com.qux.rest.AppREST - create() > User User [id=-1, email=guest@quant-ux.com, role=guest] tried to  create /rest/apps/
quant-ux-backend | AppREST.create() > User User [id=-1, email=guest@quant-ux.com, role=guest] tried to  create /rest/apps/
```
Any ideas?

**Comment by KlausSchaefers** [comment]
Hi, 

after the signup the user was not logged in. The signup flow in the OpenSource version and public version are a little different. This has caused the issue. It is fixed now.

**Comment by bmcgonag** [comment]
Ok, cool. I'll rebuild the images in a bit and try it again.  Thank you.

**Comment by bmcgonag** [comment]
SUCCESS!  Woot!
I have it working, again, no web-socket yet, but the software appears to work. I'm not able to tell if it's savign my profile changes. No feed back on button click, but no error that I see int he terminal. 

Anyway, so you want me to push this to DockerHub, and do you want to include the Dockerfiles and docker-compose in your repo?  Or would you like me to push it to dockerhub, and let you pull and run it to test first, so I can do any clean up?

**Comment by bmcgonag** [comment]
Ok, need you to pull the docker version down and make sure it's all working as you expect. 

Use this docker-compose.yml file:

```
version: '3'

services:
  mongo:
    restart: always
    container_name: quant-ux-mongo
    image: mongo
    volumes:
      - ./data:/data/db
  qux-fe:
    restart: always
    container_name: quant-ux-frontend
    image: qux-fe
    environment:
      - QUX_PROXY_URL=http://qux-be:8080
    links:
      - mongo
      - qux-be
    ports:
      - 8082:8082
    depends_on:
      - qux-be
  qux-be:
    restart: always
    container_name: quant-ux-backend
    image: qux-be
    environment:
      - QUX_HTTP_HOST=http://qux-fe:8082
      - QUX_HTTP_PORT=8080
      - QUX_MONGO_DB_NAME=quantux
      - QUX_MONGO_TABLE_PREFIX=quantux
      - QUX_MONGO_CONNECTION_STRING=mongodb://mongo:27017
      - QUX_MAIL_USER=mail_admin@example.com
      - QUX_MAIL_PASSWORD=sTr0ngPa55w0Rd
      - QUX_MAIL_HOST=mail.example.com
      - QUX_JWT_PASSWORD=some-long-string-of-mix-case-chars-and-nums
      - QUX_IMAGE_FOLDER_USER=/qux-images
      - QUX_IMAGE_FOLDER_APPS=/qux-image-apps
      - TZ=America/Chicago
    depends_on:
      - mongo
```

If you leave everything as it is, you should be able to access it via localhost:8082, or the IP of the host on port 8082.  The way i've set the proxy envs allows the front and back ends to talk over their docker network.  You may want / need to change the TZ, and of course the password placeholders, etc.

**Comment by KlausSchaefers** [comment]
Hi,

that is great news! Could you share the docker and docker-compose files or publish them in a own repo? One question. Which mongo version did you use?

I will try to test later

**Comment by KlausSchaefers** [comment]
Hi,

I could start the docker-compose and it seems to work! Thanks for the help!

**Comment by bmcgonag** [comment]
I have created the repository at https://github.com/bmcgonag/quant-ux-docker.  Everything is uploaded and ready. Please, when you have time, take a look at the files, and the Readme and make sure it all looks good.   Feel free to close this issue if you are happy with it.

**Comment by KlausSchaefers** [comment]
Thanks. If I find some time, I will try to automate the Docker building with GitHub actions and also add the WebSockert server. Thanks for you great help!
