### ISSUE TITLE
Allow zoom using trackpad

### ISSUE THREAD

**Issue by 12people** [KlausSchaefers/quant-ux#7]
It'd be great to be able to zoom in and out using the trackpad.

I'm using Firefox 77 under macOS and it doesn't work.

**Comment by KlausSchaefers** [comment]
Hi,

you need to press CMD / CTRL while using the mousepad. I just checked on my box and it works fine. If not, please reopen and I will have a deeper look.

**Comment by 12people** [comment]
I guess I should have been more specific – I was referring to the pinch-to-zoom gesture.
I wasn't even aware of a Cmd + scroll shortcut (it doesn't seem to be communicated anywhere in the UI) and the pinch-to-zoom gesture would feel much more natural (as it's a standard used in both desktop apps and even in other web apps, like Figma or Miro).

**Comment by KlausSchaefers** [comment]
OK, I will see what I can do. Makes sense.

**Comment by 12people** [comment]
Awesome, thanks a ton! :)
