### ISSUE TITLE
dynamically change widget properties during editing ,

### ISSUE THREAD

**Issue by Zemera** [KlausSchaefers/quant-ux#74]
Hi klaus , I'm a young professional in the field of ux desgin and test , I saw your nice work and I really appreciate it. Indeed I am working on a research project on prototype testing and I have cloned your repository but I would like to know how I can change the properties of the widgets that is in the editor, for example: if I add a button, how to change its color or its position when it is added in the editor. Thanks

**Comment by KlausSchaefers** [comment]
Hi,

once you have selected a widget, you can select it by clicking on it. Then the properties should be shown on the left side.

![image](https://user-images.githubusercontent.com/7108416/160129579-1643b005-0c2f-4716-a9ef-11bb543d3782.png)

The position can be changed with drag'n'drop.

Check out the videos:

https://www.youtube.com/channel/UCn_pvKI_8SuBuVNz3k9tTsA/videos

Does this help?
