### ISSUE TITLE
Scroll bar not showing for Table

### ISSUE THREAD

**Issue by BirukTes** [KlausSchaefers/quant-ux#78]
Hi,

Thank you for this awesome product. 

Text area scroll bar seems to work but not Table, as can be seen from the pictures below. Could you please tell us we what we can do to display scrollable tabular data?

![image](https://user-images.githubusercontent.com/23151263/167443001-0ae3da42-bd71-4941-b3ee-c48e5a66a29d.png)
![image](https://user-images.githubusercontent.com/23151263/167443161-9d1885c7-bd75-4dea-8405-120451eb0731.png)

**Comment by KlausSchaefers** [comment]
Hi,

overflows are currently not supported. There is maybe one "quick" fix:

1) Instead of the table, add a "Screen Segment"

2) Create a new screen & and set it to be a "segment screen"

3) Add the table to the new screen

4) Link the screen segment to the new screen.

I will add overflow support in the next weeks.

**Comment by KlausSchaefers** [comment]
https://user-images.githubusercontent.com/7108416/167445505-a54e2c12-2e10-4a0c-8474-019d1e8ae600.mp4

**Comment by BirukTes** [comment]
> Hi,
> 
> overflows are currently not supported. There is maybe one "quick" fix:
> 
> 1. Instead of the table, add a "Screen Segment"
> 2. Create a new screen & and set it to be a "segment screen"
> 3. Add the table to the new screen
> 4. Link the screen segment to the new screen.
> 
> I will add overflow support in the next weeks.

Fantastic, this too should work, it even looks like a table except the header is scrolling with. We were also not aware of being able to render screen segments inside of another screen, this will be handy.  Thank you.

**Comment by KlausSchaefers** [comment]
Hi,

tables are now scrollable and you can set headers to be sticky...

![Qux_Stikcy_header](https://user-images.githubusercontent.com/7108416/168483183-8446dc93-a632-4eac-9325-4d4f97e96cbc.png)

**Comment by BirukTes** [comment]
We will check it, thank you for the quick update.
