### ISSUE TITLE
 it would be great to be able to show and hide the Wieget via code

### ISSUE THREAD

**Issue by jzzhrqp** [KlausSchaefers/quant-ux#79]
Hello KlausSchaefers！ thank you for open source this tool, it works great, thank you! How to control the display and hide of Wiget through code? I know it's great to be able to control the display by jumping to other screens, but it would be great to be able to show and hide the Wieget via code。

**Comment by KlausSchaefers** [comment]
This is a tricky one, how would you expect the rest of the UI to behave? Collapse like HTML does? Or just show and hide?

**Comment by KlausSchaefers** [comment]
Hi, was thinking a little. Code is a nice idea, but this will take me quite some time to get it right. I will keep you posted in here.

**Comment by KlausSchaefers** [comment]
@jzzhrqp Please check out issue 80

**Comment by jzzhrqp** [comment]
Thank you for your positive reply. I also saw your discussion on issue 80. I think it has included my question. Everything is moving towards a better direction. I am looking forward to what you will do. Thank you!

**Comment by KlausSchaefers** [comment]
I am nearly done with the scripting functionality. Hiding and showing widgets will come next.

https://user-images.githubusercontent.com/7108416/175833305-eecf5edc-b4c8-49dc-b570-8bcbfe83b109.mp4
