### ISSUE TITLE
Missing layer panel

### ISSUE THREAD

**Issue by dohspendos** [KlausSchaefers/quant-ux#87]
I have [bmcgonag/quant-ux-docker](https://github.com/bmcgonag/quant-ux-docker) up and running. However the layers panel on  the left does not exist. How do I enable/view the layer panel.

**Comment by KlausSchaefers** [comment]
You can change the view options when you click on the zoom menu in the top
right.

dohspendos ***@***.***> schrieb am Sa., 25. Juni 2022, 01:19:

**Comment by KlausSchaefers** [comment]
![image](https://user-images.githubusercontent.com/7108416/175833373-9d031aa0-5af0-4599-ad90-d3e2f78a797d.png)
