### ISSUE TITLE
Permit Rest-widget to be an implicit before--first-screen widget

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#91]
So that you can load all sorts of dynamic data from a server, with no need to build a dummy first-screen (now the Rest widget has to be placed in transition between two screens).

**Comment by KlausSchaefers** [comment]
Check this: https://quant-ux.com/#/help/scripts.html. You should be able to do a fetch in JS

**Comment by Equilibrier** [comment]
Ok, let's assume I want to prototype a list, based on some dynamic data already fetched with a Rest component, and which is stored in a binded variable, called "data.items" which is an array.
The UI list is limited, 4 rows per screen, but I want to make pagination for it (1) and (2) I want each of the item be a simple text in its row, or a strikethrough text  based on some flag, like a data.items[i].done.
Are (1) and (2) possible with <> component now ? How would you do it ?

PS: I need to find out if with some effort I can maintain a session state-full app simulation on prototyping with QuantUX, or should I just simulate some predefined scenario. This is what I try to check next, and the <> component really triggered my attention for this.
So, I could use Rest components to call some GET endpoints on my server, to be able to persist some app operations and store the state on a simple python flask app (my server). If it could be possible to maintain a session-only full-app-state with only quantUX, please do tell me, I'm curious myself, but if not, if I would just use Rest endpoints for persistency, do you think this is feasible enough for all sorts of dynamic behavior ?

Thanks a lot !

**Comment by KlausSchaefers** [comment]
Hi,

scripts should be able to do fetch() calls. If you want to pass data between components you need to use the data binding mechanism. So the output of the REST could be "restResult" and the Script could access it with "data.restResult"
