### ISSUE TITLE
Auto-transition after N miliseconds

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#92]
A new transition type, which is automatic (without any click or keypress) and triggers after a certain delay would be useful. Figma has this and there are situations where you want to simulate a splash like screen on a client and you need such transition.

**Comment by KlausSchaefers** [comment]
Time transitions are already available for screens...

![image](https://user-images.githubusercontent.com/7108416/176376968-0b82c3ce-2141-44e3-bf6a-c0266b144a0f.png)
