### ISSUE TITLE
Multiple selections; multiple screens/components move on the canvas

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#94]
If I need to rearrange the screens/components a little, so that I can have a more intuitive layout, it seems I cannot do the basic intuitive operations.
(1)You can select multiple components from the canvas with mouse&drag but you cannot move them in block afterwards.
(2)You cannot select multiple screens from the canvas, with mouse-drag (it selects only the first screen)
(3) You can select multiple screens from the canvas, using SHIFT+click on the layout-panel, multiple times (kind of inconvenient but it works) but then on, you cannot move that selection to another place on the canvas

These operations would be very useful if enabled/implemented.

**Comment by KlausSchaefers** [comment]
This is a know limitation and will not be fixed anytime soon :(
