### ISSUE TITLE
Panning on canvas with mouse

### ISSUE THREAD

**Issue by Equilibrier** [KlausSchaefers/quant-ux#97]
It would have been great if quantUX could make the panning and zooming through the canvas easy enough to be done with just the mouse, and not by using the scrools. In Figma this is done with pressing the middle mouse button. In QuantUX this seems to work also (only sometimes), but the panning is only on the vertical axis, and it is a slippy panning, not a progressive, "perspective correct" one.

**Comment by KlausSchaefers** [comment]
Hi,

You can press <Space> to move the canvas.

with a Mac touch pad this work very well. What are you using?

**Comment by Equilibrier** [comment]
I saw the move-canvas tool afterwards, and the space bar. So the feature is there and well implemented. Will close this issue. Sorry for this.

**Comment by Equilibrier** [comment]
already implemented with spacebar keypress/move-canvas tool
